---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
#  ansible-lint
#  flake8
platforms:
  - name: kind-default
    groups:
      - k8s
    image: bsycorp/kind:latest-1.12
    privileged: True
    override_command: no
    exposed_ports:
      - 8443/tcp
      - 10080/tcp
    published_ports:
      - 0.0.0.0:${TEST_CLUSTER_PORT:-9443}:8443/tcp
    pre_build_image: yes
provisioner:
  name: ansible
  log: True
  inventory:
    group_vars:
      all:
        namespace: ${TEST_NAMESPACE:-osdk-test}
  env:
    K8S_AUTH_KUBECONFIG: /tmp/molecule/kind-default/kubeconfig
    KUBECONFIG: /tmp/molecule/kind-default/kubeconfig
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
    KIND_PORT: "${TEST_CLUSTER_PORT:-9443}"
scenario:
  name: default
verifier:
  name: testinfra
