- name: Run cert
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    OPERATOR_NAME: ibm-spectrum-scale-csi-operator
    OPERATOR_VERSION: 1.1.0
    OPERATOR_DIR: ../../operator/
    OP_PKG: ibm-spectrum-scale-csi-operator-app.zip
    ADDITIONAL_RESOURCES: ["service_account.yaml", "role_binding.yaml"]
    CRD_LIST: ["ibm-spectrum-scale-csi-operator-crd.yaml"]
    CR_LIST: ["ibm-spectrum-scale-csi-operator-cr.yaml"]
    SC_VARS: "--config .osdk-scorecard.yaml"

  tasks:
    - name: Ensure Operator is verified
      include_tasks: cert/verify_operator.yaml
