- name: Deploy operator
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Ensure common tasks are run
      include_tasks: common/dev-env.yaml

    - name: Ensure Operator is verified
      include_tasks: deploy/preflight.yaml
