- name: Dynamically Generate Installer Files
  hosts: localhost
  gather_facts: false

  vars:
    repo_root_dir: "{{ playbook_dir }}/../../"
    operator_dir: "{{ repo_root_dir }}/operator"

    generated_dir: "{{ repo_root_dir }}/generated/installer"
  
    filename: "{{ 'ibm-spectrum-scale-csi-operator.test.yaml' if travis_testing else 'ibm-spectrum-scale-csi-operator.yaml' }}"
    filename_dev: 'ibm-spectrum-scale-csi-operator-dev.yaml'
    generated_op_yaml: "{{ generated_dir }}/{{ filename }}"
    generated_op_dev_yaml: "{{ generated_dir }}/{{ filename_dev }}"
    operator_files: 
      - name: "deploy/operator.yaml"
      - name: "deploy/role.yaml"
      - name: "deploy/role_binding.yaml"
      - name: "deploy/service_account.yaml"
      - name: "deploy/crds/csiscaleoperators.csi.ibm.com.crd.yaml"

    # Copy over the non modified file to the installer directory
    non_generated: false
    # Set to true to test Travis
    travis_testing: false

  tasks:
    - name: Create files to help manually install the operator
      include_tasks: generate/create_files.yaml
