- name: Run OLM test
  hosts: localhost
  become: yes
  gather_facts: false
  vars:

    # https://quay.io/repository/vrushch/vrushal-csi-driver-repo-2
    # In above ${QUAY_NAMESPACE} = vrushch, ${PACKAGE_NAME} = vrushal-csi-driver-repo-2
    
    QUAY_NAMESPACE: vrushch
    PACKAGE_NAME: vrushal-csi-driver-repo-3

    OPERATOR_VERSIONS:
      - 1.0.0
      - 1.1.0
      - 2.0.0
      - 2.1.0

    # Need not to be changed
    CHANNEL_NAME: latest

    OPERATOR_DIR:  /root/ibm-spectrum-scale-csi/operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator
    #It can also be /root/demo/community-operators/community-operators/ibm-spectrum-scale-csi-operator

    # Do not change following variables
    NAMESPACE: "olm"
    NAMESPACE_OPERATOR: "ibm-spectrum-scale-csi-driver"
    INTERACTABLE: true
    K8S_SUB: "./olm-test/k8s-sub.yaml.j2"
    SUB: "/tmp/olm-sub"
    K8S_NS: "./olm-test/k8s-ns.yaml.j2"
    NS: "/tmp/olm-ns"
    K8S_CATALOG: "./olm-test/k8s-catalog.yaml.j2"
    CATALOG: "/tmp/olm-catalog"

  tasks:
    - name: "Get timestamp"
      shell: "date +%s"
      register: tstamp

    - name: "Determing directory for temporary package"
      set_fact: 
        olm_dir: "/tmp/{{PACKAGE_NAME}}-{{tstamp.stdout}}"

    - name: "Create the directory {{ olm_dir }}"
      file:
        path: "{{ olm_dir }}"
        state: directory
        mode: '0755'

    - name: "Ensure subscription file is defined for consumption"
      template: 
        src: "{{ K8S_SUB }}"
        dest: "{{ SUB }}"
    
    - name: "Ensure namespace and operatorgroup file is defined for consumption"
      template:
        src: "{{ K8S_NS }}"
        dest: "{{ NS }}"

    - name: "Ensure catalogsource file is defined for consumption"
      template:
        src: "{{ K8S_CATALOG }}"
        dest: "{{ CATALOG }}"

    - name: "Iterate  over the operator versions."
      include_tasks: "./olm-test/k8s-check-version-play.yaml"
      loop: "{{ OPERATOR_VERSIONS }}" 

    - name: "Remove the file {{SUB}}"
      file:
        path: "{{ SUB }}"
        state: absent

    - name: "Remove the file {{NS}}"
      file:
        path: "{{ NS }}"
        state: absent

    - name: "Remove the file {{CATALOG}}"
      file:
        path: "{{ CATALOG }}"
        state: absent

    - name: "Remove the directory {{ olm_dir }}"
      file:
        path: "{{ olm_dir }}"
        state: absent
        mode: '0755'

