- name: Update Version
  hosts: localhost
  become: yes
  gather_facts: true
  vars:
    VERSION_OLD: "2.0.0"
    VERSION_NEW: "2.0.0"
    OPERATOR_DIR: "../../operator/"
    OLM_DIR: "deploy/olm-catalog/ibm-spectrum-scale-csi-operator/"
    OPERATOR_NAME: "ibm-spectrum-scale-csi-operator"
  tasks:

  - set_fact:
      CSV_OLD: "{{OLM_DIR}}{{VERSION_NEW}}/ibm-spectrum-scale-csi-operator.v{{VERSION_OLD}}.clusterserviceversion.yaml"
      CSV_NEW: "{{OLM_DIR}}{{VERSION_NEW}}/ibm-spectrum-scale-csi-operator.v{{VERSION_NEW}}.clusterserviceversion.yaml"

  - name: "Copy the CSV {{VERSION_OLD}} to {{VERSION_NEW}}"
    copy:
      src:  "{{OPERATOR_DIR}}/{{OLM_DIR}}{{VERSION_OLD}}/"
      dest: "{{OPERATOR_DIR}}/{{OLM_DIR}}{{VERSION_NEW}}"

  - name: "Rename CSV"
    copy:
      src:  "{{OPERATOR_DIR}}/{{CSV_OLD}}"
      dest: "{{OPERATOR_DIR}}/{{CSV_NEW}}"

  - name: "Remove invalid CSV"
    file:
      state: absent
      path:  "{{OPERATOR_DIR}}/{{CSV_OLD}}"

  - name: "Bump Version"
    replace: 
      path: "{{OPERATOR_DIR}}/{{item}}"
      regexp:  "{{VERSION_OLD}}"
      replace: "{{VERSION_NEW}}"
    loop:
      - "{{CSV_NEW}}"
      - "{{OLM_DIR}}/ibm-spectrum-scale-csi-operator.package.yaml"
      - deploy/operator.yaml
      - .osdk-scorecard.yaml
      - hacks/package_operator.py
      - hacks/csv_copy_cr.py
      - hacks/csv_copy_crd_descriptions.py
      - hacks/csv_copy_docs.py
      - hacks/csv_prep.py
      # Driver files.
      - ../driver/build/Dockerfile
      - ../driver/build/multi-arch.Dockerfile
      - ../driver/cmd/ibm-spectrum-scale-csi/main.go

  - name: "Rebuild operator 'ClusterServiceVersion'"
    shell: "GO111MODULE=on operator-sdk generate csv --operator-name {{OPERATOR_NAME}} --csv-version {{VERSION_NEW}} --update-crds"
    args:
      chdir: "{{OPERATOR_DIR}}"
  
