apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-advance-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-csi-advance
