apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-advance-compress
provisioner: spectrumscale.csi.ibm.com
parameters:
    type: "advanced"
    volBackendFs: "gpfs0"
    compression: "true"
reclaimPolicy: Delete

