apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-advance-tier
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "gpfs0"
    type: "advanced"
    tier: "system"
reclaimPolicy: Delete

