apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-static-pvc-dependent-2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-csi-static-dependent

