apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-fileset-dependent
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "gpfs0"
    clusterId: "7118073361626808055"
    filesetType: "dependent"
    parentFileset: "independent-fileset-gpfs0-fset1"
reclaimPolicy: Delete
