kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ibm-scale-cache-s3-ro
provisioner: spectrumscale.csi.ibm.com
parameters:
  csi.storage.k8s.io/provisioner-secret-name: ${pvc.name}-secret
  csi.storage.k8s.io/provisioner-secret-namespace: ${pvc.namespace}
  volBackendFs: "remote-sample"
  caching: "true"
  protocol: "s3"
  mode: "ro"
  #PrefetchThreshold: "50"
  #cacheTemplate: "training|fine-tuning|inference"
reclaimPolicy: Delete
