apiVersion: v1
kind: Pod
metadata:
  name: csi-afmdemo-pod
  namespace: default
  labels:
    app: nginx
spec:
  containers:
   - name: web-server
     image: gcr.io/google-containers/nginx
     volumeMounts:
       - name: mypvc
         mountPath: /usr/share/nginx/html/scale
     ports:
     - containerPort: 80
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: scale-pvc-afm
       readOnly: false

