apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: default
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-csi-provisioner
  namespace: ibm-spectrum-scale-csi
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
