apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-fileset
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "gpfs0"
    nodeClass: "ibm-spectrum-scale-nodeclass"
reclaimPolicy: Delete
