apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scale-static-pvc
  annotations:
    spectrumscale.csi.ibm.com/filesetName: "custom-fileset-static"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-csi-static-dependent
