apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-static
provisioner: spectrumscale.csi.ibm.com
parameters:
    volBackendFs: "fs1"
    existingVolume: "yes"
reclaimPolicy: Delete