apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
    release: ibm-spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi-operator
  namespace: ibm-spectrum-scale-csi-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
  template:
    metadata:
      annotations:
        productID: ibm-spectrum-scale-csi-operator
        productName: IBM Spectrum Scale CSI Operator
        productVersion: 2.2.0
      labels:
        app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
        app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
        app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
        name: ibm-spectrum-scale-csi-operator
        product: ibm-spectrum-scale-csi
        release: ibm-spectrum-scale-csi-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: Exists
      containers:
      - args:
        - --metrics-addr=0.0.0.0:8383
        - --enable-leader-election
        - --leader-election-id=ibm-spectrum-scale-csi-operator
        env:
        - name: MAX_CONCURRENT_RECONCILES_CSISCALEOPERATOR_CSI_IBM_COM
          value: "1"
        - name: MAX_CONCURRENT_RECONCILES_SECRET_
          value: "1"
        - name: ANSIBLE_DEBUG_LOGS
          value: "False"
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CSI_DRIVER_IMAGE
          value: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver:dev
        image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator:dev
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ./health_check.sh
          initialDelaySeconds: 10
          periodSeconds: 30
        name: operator
        readinessProbe:
          exec:
            command:
            - ./health_check.sh
          initialDelaySeconds: 3
          periodSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1001
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
      serviceAccountName: ibm-spectrum-scale-csi-operator
      volumes:
      - emptyDir: {}
        name: runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
    release: ibm-spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - persistentvolumeclaims
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - secrets/status
  - services/finalizers
  - serviceaccounts
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - ibm-spectrum-scale-csi-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
- apiGroups:
  - csi.ibm.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - '*'
- apiGroups:
  - storage.k8s.io
  resources:
  - volumeattachments
  - storageclasses
  - csidrivers
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
    release: ibm-spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ibm-spectrum-scale-csi-operator
subjects:
- kind: ServiceAccount
  name: ibm-spectrum-scale-csi-operator
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    product: ibm-spectrum-scale-csi
    release: ibm-spectrum-scale-csi-operator
  name: ibm-spectrum-scale-csi-operator
  namespace: ibm-spectrum-scale-csi-driver
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    release: ibm-spectrum-scale-csi-operator
  name: csiscaleoperators.csi.ibm.com
spec:
  additionalPrinterColumns:
  - JSONPath: .status.conditions[?(@.type="Ready")].status
    description: The Nginx Status
    name: Ready
    type: string
  group: csi.ibm.com
  names:
    categories:
    - scale
    kind: CSIScaleOperator
    listKind: CSIScaleOperatorList
    plural: csiscaleoperators
    singular: csiscaleoperator
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            attacher:
              description: Attacher image for csi (actually attaches to the storage).
              type: string
            attacherNodeSelector:
              description: Node selector for attacher sidecar.
              items:
                properties:
                  key:
                    description: Key for node selector.
                    type: string
                  value:
                    description: Value for key.
                    type: string
                type: object
              type: array
            clusters:
              description: A collection of gpfs cluster properties for the csi driver
                to mount.
              items:
                properties:
                  cacert:
                    description: A string specifying a cacert resource name.
                    type: string
                  id:
                    description: The cluster id of the gpfs cluster specified (mandatory).
                    type: string
                  primary:
                    description: The primary file system for the GPFS cluster.
                    properties:
                      inodeLimit:
                        description: Inode limit for Primary Fileset.
                        type: string
                      primaryFs:
                        description: The name of the primary filesystem.
                        type: string
                      primaryFset:
                        description: The name of the primary fileset, created in primaryFs.
                        type: string
                      remoteCluster:
                        description: Remote cluster ID.
                        type: string
                    type: object
                  restApi:
                    description: A collection of targets for REST calls.
                    items:
                      properties:
                        guiHost:
                          description: The hostname of the REST server.
                          type: string
                        guiPort:
                          description: The port number running the REST server.
                          type: integer
                      type: object
                    type: array
                  secrets:
                    description: A string specifying a secret resource name.
                    type: string
                  secureSslMode:
                    description: Require a secure SSL connection to connect to GPFS.
                    type: boolean
                type: object
              required:
              - id
              type: array
            driverRegistrar:
              description: Sidecar container image for the csi spectrum scale plugin
                pods.
              type: string
            imagePullSecrets:
              description: A passthrough option that distributes an imagePullSecrets
                array to the containers generated by the csi scale operator. Please
                refer to official k8s documentation for your environment for more
                details.
              items:
                type: string
              type: array
            kubeletRootDirPath:
              description: The kubelet root directory path.
              type: string
            nodeMapping:
              description: Mapping of K8s node with SpectrumScale node.
              items:
                properties:
                  k8sNode:
                    description: K8s node name.
                    type: string
                  spectrumscaleNode:
                    description: SpectrumScale node name.
                    type: string
                type: object
              type: array
            pluginNodeSelector:
              description: Node selector for SpectrumScale CSI Plugin.
              items:
                properties:
                  key:
                    description: Key for node selector.
                    type: string
                  value:
                    description: Value for key.
                    type: string
                type: object
              type: array
            provisioner:
              description: Provisioner image for csi (actually issues provision requests).
              type: string
            provisionerNodeSelector:
              description: Node selector for provisioner sidecar.
              items:
                properties:
                  key:
                    description: Key for node selector.
                    type: string
                  value:
                    description: Value for key.
                    type: string
                type: object
              type: array
            scaleHostpath:
              description: The path to the gpfs file system mounted on the host machine.
              type: string
            secretCounter:
              description: An internal counter used by the operator to trigger reloads
                on secret change.
              type: integer
            snapshotter:
              description: Snapshotter image for csi (issues volume snapshot requests).
              type: string
            snapshotterNodeSelector:
              description: Node selector for snapshotter sidecar.
              items:
                properties:
                  key:
                    description: Key for node selector.
                    type: string
                  value:
                    description: Value for key.
                    type: string
                type: object
              type: array
            spectrumScale:
              description: Image name for the csi spectrum scale plugin container.
              type: string
            tolerations:
              description: Array of tolerations that will be distribued to CSI pods.
                Please refer to official k8s documentation for your environment for
                more details.
              items:
                properties:
                  effect:
                    description: Valid values are "NoSchedule", "PreferNoSchedule"
                      and "NoExecute". An empty effect matches all effects with given
                      key.
                    enum:
                    - NoSchedule
                    - PreferNoSchedule
                    - NoExecute
                    - ""
                    type: string
                  key:
                    description: Node taint key name
                    type: string
                  operator:
                    description: Valid values are "Exists" and "Equal".
                    enum:
                    - Exists
                    - Equal
                    type: string
                  tolerationSeconds:
                    description: Used only when effect is "NoExecute". It determines
                      how long the pod will stay bound to the node after the taint
                      is added.
                    type: integer
                  value:
                    description: Required if operator is "Equal"
                    type: string
                required:
                - key
                - operator
                - effect
                type: object
              type: array
            trigger:
              description: A generic trigger to be used in kickin off the ansible
                operator.
              type: string
          required:
          - scaleHostpath
          type: object
        status:
          properties:
            conditions:
              description: The active status of the operator
              items:
                properties:
                  Ready:
                    description: Indicates that the plugin is running.
                    type: boolean
                type: object
              type: array
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
