- name: "Copy directory {{item}}"
  copy: 
    src: "{{OPERATOR_DIR}}/{{item}}"
    dest: "{{ olm_dir }}/olm-catalog/ibm-spectrum-scale-csi-operator/"

- name: "Write the updated package"
  template: 
    src: "ibm-spectrum-scale-csi-operator.package.yaml.j2"
    dest: "{{ olm_dir }}/olm-catalog/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml"

- name: "Copy docker file"
  template:
    src: "Dockerfile"
    dest: "{{ olm_dir }}/Dockerfile"


- name: "build image"
  shell: 'cd {{ olm_dir }};podman build . --rm -t quay.io/{{QUAY_NAMESPACE}}/{{PACKAGE_NAME}}:{{CHANNEL_NAME}};sleep 15'

- name: "push image"
  shell: 'cd {{ olm_dir }};podman push quay.io/{{QUAY_NAMESPACE}}/{{PACKAGE_NAME}}:{{CHANNEL_NAME}}  --creds {{QUAY_USERNAME}}:{{QUAY_PASSWORD}} ; sleep 15'
  
- name: "Consume subscription"
  shell: 
    cmd: " oc delete -f {{SUB}}; sleep 10; oc apply -f {{SUB}};  "

- pause:
    prompt: "OLM configured to use {{item}}, press enter to continue"
    echo: no
  when: INTERACTABLE
