apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: ibm-spectrum-scale-csi-advance-expansion
provisioner: spectrumscale.csi.ibm.com
parameters:
    version: "2"
    volBackendFs: "gpfs0"
reclaimPolicy: Delete
allowVolumeExpansion: true
