apiVersion: v1
kind: PersistentVolume
metadata:
        name: static-scale-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: "0;2;1925837219448245938;0A0B55AC:60704F6C;;pvc-9e6d9c29-3360-4e58-9237-d9d8390eb22d;/ibm/gpfs0/spectrum-scale-csi-volume-store/.volumes/pvc-9e6d9c29-3360-4e58-9237-d9d8390eb22d"
