
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators/finalizers
  verbs:
  - update
- apiGroups:
  - csi.ibm.com
  resources:
  - csiscaleoperators/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - get
  - list
  - patch
  - watch
