apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotContent
metadata:
  name: ibm-spectrum-scale-snapshot-content
spec:
  deletionPolicy: Delete
  driver: spectrumscale.csi.ibm.com
  source:
    snapshotHandle: 18133600329030594550;0A1501E9:5F02F150;pvc-79e82f45-1b25-4d83-8ed0-c0d370cad5bd;ibm-spectrum-scale-snapshot
  volumeSnapshotRef:
    name: ibm-spectrum-scale-snapshot
    namespace: default
