apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ibm-spectrum-scale-pvc-from-snapshot-static
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibm-spectrum-scale-csi-static
  dataSource:
    name: ibm-spectrum-scale-snapshot-static
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
