// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccessToken access token
//
// swagger:model AccessToken
type AccessToken struct {

	// access token
	AccessToken string `json:"accessToken,omitempty"`

	// auth data
	AuthData *AuthData `json:"authData,omitempty"`

	// last status change
	LastStatusChange *FsccDate `json:"lastStatusChange,omitempty"`

	// requesting user
	RequestingUser string `json:"requestingUser,omitempty"`
}

// Validate validates this access token
func (m *AccessToken) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAuthData(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastStatusChange(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccessToken) validateAuthData(formats strfmt.Registry) error {

	if swag.IsZero(m.AuthData) { // not required
		return nil
	}

	if m.AuthData != nil {
		if err := m.AuthData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("authData")
			}
			return err
		}
	}

	return nil
}

func (m *AccessToken) validateLastStatusChange(formats strfmt.Registry) error {

	if swag.IsZero(m.LastStatusChange) { // not required
		return nil
	}

	if m.LastStatusChange != nil {
		if err := m.LastStatusChange.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("lastStatusChange")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccessToken) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccessToken) UnmarshalBinary(b []byte) error {
	var res AccessToken
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
