// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CESSummary Summary information about CES
//
// swagger:model CESSummary
type CESSummary struct {

	// The CES address policy
	AddressPolicy string `json:"addressPolicy,omitempty"`

	// The CES shared root directory
	CesSharedRoot string `json:"cesSharedRoot,omitempty"`

	// A list of enabled CES services
	EnabledServices string `json:"enabledServices,omitempty"`

	// The log level of CES
	LogLevel int32 `json:"logLevel,omitempty"`
}

// Validate validates this c e s summary
func (m *CESSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CESSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CESSummary) UnmarshalBinary(b []byte) error {
	var res CESSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
