// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CallHomeInlineResponse200 call home inline response200
//
// swagger:model CallHomeInlineResponse200
type CallHomeInlineResponse200 struct {

	// call home config
	CallHomeConfig *CallHomeConfig `json:"callHomeConfig,omitempty"`

	// The status of the request
	Status *RequestStatus `json:"status,omitempty"`
}

// Validate validates this call home inline response200
func (m *CallHomeInlineResponse200) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCallHomeConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CallHomeInlineResponse200) validateCallHomeConfig(formats strfmt.Registry) error {

	if swag.IsZero(m.CallHomeConfig) { // not required
		return nil
	}

	if m.CallHomeConfig != nil {
		if err := m.CallHomeConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("callHomeConfig")
			}
			return err
		}
	}

	return nil
}

func (m *CallHomeInlineResponse200) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CallHomeInlineResponse200) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CallHomeInlineResponse200) UnmarshalBinary(b []byte) error {
	var res CallHomeInlineResponse200
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
