// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CosUploadParams Object with parameters for COS upload
//
// swagger:model CosUploadParams
type CosUploadParams struct {

	// Upload all files to COS
	All bool `json:"all,omitempty"`

	// Upload specified files only to COS
	ObjectList []string `json:"objectList"`

	// Path to a dedicated directory in a fileset. You can skip this parameter to use default link path of your fileset
	Path string `json:"path,omitempty"`
}

// Validate validates this cos upload params
func (m *CosUploadParams) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CosUploadParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CosUploadParams) UnmarshalBinary(b []byte) error {
	var res CosUploadParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
