// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DefaultPlan default plan
//
// swagger:model DefaultPlan
type DefaultPlan struct {

	// approval
	Approval *bool `json:"approval,omitempty"`

	// rate limit
	RateLimit *DefaultPlanRateLimit `json:"rate-limit,omitempty"`

	// The title of the plan
	// Required: true
	Title *string `json:"title"`
}

// Validate validates this default plan
func (m *DefaultPlan) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRateLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTitle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DefaultPlan) validateRateLimit(formats strfmt.Registry) error {

	if swag.IsZero(m.RateLimit) { // not required
		return nil
	}

	if m.RateLimit != nil {
		if err := m.RateLimit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rate-limit")
			}
			return err
		}
	}

	return nil
}

func (m *DefaultPlan) validateTitle(formats strfmt.Registry) error {

	if err := validate.Required("title", "body", m.Title); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DefaultPlan) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefaultPlan) UnmarshalBinary(b []byte) error {
	var res DefaultPlan
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// DefaultPlanRateLimit default plan rate limit
//
// swagger:model DefaultPlanRateLimit
type DefaultPlanRateLimit struct {

	// hard limit
	HardLimit *bool `json:"hard-limit,omitempty"`

	// value
	Value *string `json:"value,omitempty"`
}

// Validate validates this default plan rate limit
func (m *DefaultPlanRateLimit) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DefaultPlanRateLimit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DefaultPlanRateLimit) UnmarshalBinary(b []byte) error {
	var res DefaultPlanRateLimit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
