// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FilesetUsage Summary information about a fileset usage
//
// swagger:model FilesetUsage
type FilesetUsage struct {

	// Specifies the allocated inodes for this fileset
	AllocatedInodes int64 `json:"allocatedInodes,omitempty"`

	// Specifies the free inodes for this fileset
	InodeSpaceFreeInodes int64 `json:"inodeSpaceFreeInodes,omitempty"`

	// Specifies the used inodes for this fileset
	InodeSpaceUsedInodes int64 `json:"inodeSpaceUsedInodes,omitempty"`

	// Specifies the used bytes for this fileset
	UsedBytes int64 `json:"usedBytes,omitempty"`

	// Specifies the used inodes for this fileset
	UsedInodes int64 `json:"usedInodes,omitempty"`
}

// Validate validates this fileset usage
func (m *FilesetUsage) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FilesetUsage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FilesetUsage) UnmarshalBinary(b []byte) error {
	var res FilesetUsage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
