// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FileAuditLogConfig file audit log config
//
// swagger:model FileAuditLogConfig
type FileAuditLogConfig struct {

	// The name of the filesystem where the filesets resides which contains the audit log records
	AuditFilesetDeviceName string `json:"auditFilesetDeviceName,omitempty"`

	// The name of the fileset where the audit log records are written to
	AuditFilesetName string `json:"auditFilesetName,omitempty"`

	// Number of days the audit log records are kept
	AuditRetention int32 `json:"auditRetention,omitempty"`

	// The event types configured for file audit logging
	EventTypes string `json:"eventTypes,omitempty"`

	// The topic generation number
	TopicGenNum int32 `json:"topicGenNum,omitempty"`
}

// Validate validates this file audit log config
func (m *FileAuditLogConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FileAuditLogConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FileAuditLogConfig) UnmarshalBinary(b []byte) error {
	var res FileAuditLogConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
