// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// JobRequest job request
//
// swagger:model JobRequest
type JobRequest struct {

	// The data posted when job was submitted
	Data interface{} `json:"data,omitempty"`

	// HTTP request type (GET, POST, PUT OR DELETE)
	Type string `json:"type,omitempty"`

	// The URL the job got submitted through
	URL string `json:"url,omitempty"`
}

// Validate validates this job request
func (m *JobRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *JobRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *JobRequest) UnmarshalBinary(b []byte) error {
	var res JobRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
