// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OwningFilesystem Summary information about a owning cluster filesystem
//
// swagger:model OwningFilesystem
type OwningFilesystem struct {

	// The access permissions to the owning cluster filesystem
	Access string `json:"access,omitempty"`

	// The name of the owning cluster filesystem, or 'all' when addressing all file systems of owning cluster.
	Filesystem string `json:"filesystem,omitempty"`
}

// Validate validates this owning filesystem
func (m *OwningFilesystem) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OwningFilesystem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OwningFilesystem) UnmarshalBinary(b []byte) error {
	var res OwningFilesystem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
