// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PDiskDetails Detailed information about a physical disk configuration
//
// swagger:model PDiskDetails
type PDiskDetails struct {

	// The value of field replaceable unit (FRU) of the pdisk
	Fru string `json:"fru,omitempty"`

	// The hardware type of the pdisk
	HardwareType string `json:"hardwareType,omitempty"`

	// Location of the pdisk
	Location string `json:"location,omitempty"`

	// The product name of the pdisk
	Product string `json:"product,omitempty"`

	// The value of replacement priority
	ReplacementPriority float64 `json:"replacementPriority,omitempty"`

	// The revision of the pdisk
	Revision string `json:"revision,omitempty"`

	// The value of recovery group index
	RgIndex int32 `json:"rgIndex,omitempty"`

	// The serial of the pdisk
	Serial string `json:"serial,omitempty"`

	// The server name of the ESS
	Server string `json:"server,omitempty"`

	// The speed of the pdisk
	Speed int32 `json:"speed,omitempty"`

	// The vendor name of the pdisk
	Vendor string `json:"vendor,omitempty"`

	// The value of world wide name of the pdisk
	Wwn string `json:"wwn,omitempty"`
}

// Validate validates this p disk details
func (m *PDiskDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PDiskDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PDiskDetails) UnmarshalBinary(b []byte) error {
	var res PDiskDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
