// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoteClusterInlineResponse200 remote cluster inline response200
//
// swagger:model RemoteClusterInlineResponse200
type RemoteClusterInlineResponse200 struct {

	// remoteClusters
	RemoteClusters []*RemoteCluster `json:"remoteClusters"`

	// The status of the request
	Status *RequestStatus `json:"status,omitempty"`
}

// Validate validates this remote cluster inline response200
func (m *RemoteClusterInlineResponse200) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRemoteClusters(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemoteClusterInlineResponse200) validateRemoteClusters(formats strfmt.Registry) error {

	if swag.IsZero(m.RemoteClusters) { // not required
		return nil
	}

	for i := 0; i < len(m.RemoteClusters); i++ {
		if swag.IsZero(m.RemoteClusters[i]) { // not required
			continue
		}

		if m.RemoteClusters[i] != nil {
			if err := m.RemoteClusters[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("remoteClusters" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RemoteClusterInlineResponse200) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RemoteClusterInlineResponse200) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoteClusterInlineResponse200) UnmarshalBinary(b []byte) error {
	var res RemoteClusterInlineResponse200
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
