// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RemoteFilesystemInlineResponse200 remote filesystem inline response200
//
// swagger:model RemoteFilesystemInlineResponse200
type RemoteFilesystemInlineResponse200 struct {

	// remotefilesystems
	RemoteFilesystems []*RemoteFilesystem `json:"remoteFilesystems"`

	// The status of the request
	Status *RequestStatus `json:"status,omitempty"`
}

// Validate validates this remote filesystem inline response200
func (m *RemoteFilesystemInlineResponse200) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRemoteFilesystems(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RemoteFilesystemInlineResponse200) validateRemoteFilesystems(formats strfmt.Registry) error {

	if swag.IsZero(m.RemoteFilesystems) { // not required
		return nil
	}

	for i := 0; i < len(m.RemoteFilesystems); i++ {
		if swag.IsZero(m.RemoteFilesystems[i]) { // not required
			continue
		}

		if m.RemoteFilesystems[i] != nil {
			if err := m.RemoteFilesystems[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("remoteFilesystems" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *RemoteFilesystemInlineResponse200) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	if m.Status != nil {
		if err := m.Status.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("status")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *RemoteFilesystemInlineResponse200) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RemoteFilesystemInlineResponse200) UnmarshalBinary(b []byte) error {
	var res RemoteFilesystemInlineResponse200
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
