// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SymlinkPath Summary information about a path
//
// swagger:model SymlinkPath
type SymlinkPath struct {

	// The name of the fileset the path belongs to.
	FilesetName string `json:"filesetName,omitempty"`

	// The name of the filesystem the path belongs to.
	// Required: true
	FilesystemName *string `json:"filesystemName"`

	// The directory path relative to the filesystem's mount point or to the fileset path (if specified).
	RelativePath string `json:"relativePath,omitempty"`
}

// Validate validates this symlink path
func (m *SymlinkPath) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFilesystemName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SymlinkPath) validateFilesystemName(formats strfmt.Registry) error {

	if err := validate.Required("filesystemName", "body", m.FilesystemName); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SymlinkPath) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SymlinkPath) UnmarshalBinary(b []byte) error {
	var res SymlinkPath
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
