apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Storage
    certified: "false"
    containerImage: quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator
    createdAt: Thu May 5 04:42:15 IST 2022
    description: An operator for deploying and managing the IBM Storage Scale CSI
      Driver.
    repository: https://github.com/IBM/ibm-spectrum-scale-csi/
    support: IBM
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/managed-by: ibm-spectrum-scale-csi-operator
    app.kubernetes.io/name: ibm-spectrum-scale-csi-operator
    operatorframework.io/arch.amd64: supported
    operatorframework.io/arch.ppc64le: supported
    operatorframework.io/arch.s390x: supported
  name: ibm-spectrum-scale-csi-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CSIScaleOperator is the Schema for the csiscaleoperators API
      displayName: IBM Storage Scale CSI Driver
      kind: CSIScaleOperator
      name: csiscaleoperators.csi.ibm.com
      resources:
      - kind: ConfigMap
        name: ""
        version: v1
      - kind: DaemonSet
        name: ""
        version: v1beta2
      - kind: Deployment
        name: ""
        version: v1beta2
      - kind: Pod
        name: ""
        version: v1
      specDescriptors:
      - description: affinity is a group of affinity scheduling rules.
        displayName: Affinity
        path: affinity
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: attacher is the attacher sidecar image for CSI (actually attaches
          to the storage).
        displayName: Attacher Image
        path: attacher
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: attacherNodeSelector is the node selector for attacher sidecar.
        displayName: Attacher Node Selector
        path: attacherNodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Key for node selector
        displayName: Key
        path: attacherNodeSelector[0].key
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Value for key
        displayName: Value
        path: attacherNodeSelector[0].value
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: clusters is a collection of IBM Storage Scale cluster properties
          for the CSI driver to mount.
        displayName: Clusters
        path: clusters
      - description: cacert is the name of the configMap storing GUI certificates.
          Mandatory if secureSslMode is true.
        displayName: CA Certificate Resource Name
        path: clusters[0].cacert
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:ConfigMap
      - description: id is the cluster ID of the IBM Storage Scale cluster.
        displayName: Cluster ID
        path: clusters[0].id
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: primary is the primary file system for the IBM Storage Scale cluster.
        displayName: Primary
        path: clusters[0].primary
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: restApi is a collection of targets for REST calls
        displayName: REST API
        path: clusters[0].restApi
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: guiHost is the hostname/IP of the IBM Storage Scale GUI node.
        displayName: GUI Host
        path: clusters[0].restApi[0].guiHost
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: guiPort is the port number of the IBM Storage Scale GUI node.
        displayName: GUI Port
        path: clusters[0].restApi[0].guiPort
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:number
      - description: secret is the name of the basic-auth secret containing credentials
          to connect to IBM Storage Scale REST API server.
        displayName: Secrets
        path: clusters[0].secrets
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes:Secret
      - description: secureSslMode specifies if a secure SSL connection to connect
          to IBM Storage Scale cluster is required.
        displayName: Secure SSL Mode
        path: clusters[0].secureSslMode
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:booleanSwitch
      - description: consistencyGroupPrefix is a prefix of consistency group of an
          application. This is expected to be an RFC4122 UUID value (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
          in hexadecimal values)
        displayName: Consistency Group Prefix
        path: consistencyGroupPrefix
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: PodSecurityPolicy name for CSI driver and sidecar pods.
        displayName: CSI Pod Security Policy Name
        path: csipspname
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: driverRegistrar is the Sidecar container image for the IBM Storage
          Scale CSI plugin pods.
        displayName: Driver Registrar
        path: driverRegistrar
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: A passthrough option that distributes an imagePullSecrets array
          to the containers generated by the CSI scale operator. Please refer to official
          k8s documentation for your environment for more details.
        displayName: Image Pull Secrets
        path: imagePullSecrets
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: kubeletRootDirPath is the path for kubelet root directory.
        displayName: Kubelet Root Directory Path
        path: kubeletRootDirPath
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: livenessprobe is the image for livenessProbe container (liveness
          probe is used to know when to restart a container).
        displayName: LivenessProbe
        path: livenessprobe
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: nodeMapping specifies mapping of K8s node with IBM Storage Scale
          node.
        displayName: Node Mapping
        path: nodeMapping
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: k8sNode is the name of the kubernetes node
        displayName: Kubernetes Node
        path: nodeMapping[0].k8sNode
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: spectrumscaleNode is the name of the IBM Storage Scale node
        displayName: IBM Storage Scale Node
        path: nodeMapping[0].spectrumscaleNode
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: pluginNodeSelector is the node selector for IBM Storage Scale CSI
          plugin.
        displayName: Plugin Node Selector
        path: pluginNodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Key for node selector
        displayName: Key
        path: pluginNodeSelector[0].key
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Value for key
        displayName: Value
        path: pluginNodeSelector[0].value
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: provisioner is the provisioner sidecar image for CSI (actually
          issues provision requests).
        displayName: Provisioner Image
        path: provisioner
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: provisionerNodeSelector is the node selector for provisioner
          sidecar.
        displayName: Provisioner Node Selector
        path: provisionerNodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Key for node selector
        displayName: Key
        path: provisionerNodeSelector[0].key
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Value for key
        displayName: Value
        path: provisionerNodeSelector[0].value
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: resizer is the resizer sidecar image for CSI (issues volume expansion
          requests).
        displayName: Resizer Image
        path: resizer
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: resizerNodeSelector is the node selector for resizer sidecar.
        displayName: Resizer Node Selector
        path: resizerNodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Key for node selector
        displayName: Key
        path: resizerNodeSelector[0].key
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Value for key
        displayName: Value
        path: resizerNodeSelector[0].value
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: snapshotter is the snapshotter sidecar image for CSI (issues
          volume snapshot requests).
        displayName: Snapshotter Image
        path: snapshotter
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: snapshotterNodeSelector is the snapshotter node selector for
          snapshotter sidecar.
        displayName: Snapshotter Node Selector
        path: snapshotterNodeSelector
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      - description: Key for node selector
        displayName: Key
        path: snapshotterNodeSelector[0].key
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: Value for key
        displayName: Value
        path: snapshotterNodeSelector[0].value
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: spectrumScale is the image name for the IBM Storage Scale CSI node
          driver plugin container.
        displayName: IBM Storage Scale Image
        path: spectrumScale
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:hidden
      - description: Array of tolerations that will be distributed to CSI pods. Please
          refer to official k8s documentation for your environment for more details.
        displayName: Tolerations
        path: tolerations
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:advanced
      statusDescriptors:
      - description: conditions contains the details for one aspect of the current
          state of this custom resource.
        displayName: Conditions
        path: condition
        x-descriptors:
        - urn:alm:descriptor:io.kubernetes.conditions
      version: v1
  description: |
    The IBM Storage Scale CSI Operator for Kubernetes installs, manages,
    upgrades the IBM Storage Scale CSI Driver on OpenShift and Kubernetes
    for provisioning of persistent volumes on IBM Storage Scale.

    ### Documentation Documentation for IBM Storage Scale CSI Driver and Operator can be found at [IBM Documentation](https://www.ibm.com/docs/en/spectrum-scale-csi).

    ### Getting help
    IBM Storage Scale CSI driver is part of the IBM Storage Scale offering.
    Please follow the [IBM support procedure](https://www.ibm.com/mysupport/s/?language=en_US) for any issues with the driver.

    For non-urgent issues, suggestions, recommendations feel free to open an
    issue in [github](https://github.com/IBM/ibm-spectrum-scale-csi). Issues will be addressed as team availability permits.

    **Note:** Custom Resource example represents the minimum settings needed to run
    the operator. If your environment needs more advanced settings (e.g. remote clusters,
    node mapping, image pull secret, Taint and Toleration etc.) please refer to  the sample [Custom Resource](https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.6.0/operator/config/samples/csiscaleoperators.csi.ibm.com_cr.yaml).
  displayName: IBM Storage Scale CSI Plugin Operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB2aWV3Qm94PSIwIDAgMzIgMzIiPgogIDxkZWZzPgogICAgPGxpbmVhckdyYWRpZW50IGlkPSJiMzczZDkxNi0zNWQzLTQ4NDAtOWI5Ni1jMWFhNzkyNTI4NzYiIHgxPSIxLjcxIiB5MT0iMjIuNTAyIiB4Mj0iMTcuMjkiIHkyPSIzMS40OTgiIGdyYWRpZW50VW5pdHM9InVzZXJTcGFjZU9uVXNlIj4KICAgICAgPHN0b3Agb2Zmc2V0PSIwLjIiIHN0b3Atb3BhY2l0eT0iMCIvPgogICAgICA8c3RvcCBvZmZzZXQ9IjAuNiIvPgogICAgPC9saW5lYXJHcmFkaWVudD4KICAgIDxsaW5lYXJHcmFkaWVudCBpZD0iZjZmYjQ4MDgtMDdjYS00N2RlLWI5NjYtYjkzZTQ4YWQwNGZhIiB4MT0iMzU0MS41IiB5MT0iMjciIHgyPSIzNTQxLjUiIHkyPSIxOCIgZ3JhZGllbnRUcmFuc2Zvcm09Im1hdHJpeCgxLCAwLCAwLCAtMSwgLTM1MjAsIDQ1KSIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgogICAgICA8c3RvcCBvZmZzZXQ9IjAuMiIvPgogICAgICA8c3RvcCBvZmZzZXQ9IjEiIHN0b3Atb3BhY2l0eT0iMCIvPgogICAgPC9saW5lYXJHcmFkaWVudD4KICAgIDxtYXNrIGlkPSJhZjgzNjFhYy05Y2M3LTRmN2ItYjExMi0wM2Q3ZDdhOTE0NTQiIHg9IjAiIHk9IjAiIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgbWFza1VuaXRzPSJ1c2VyU3BhY2VPblVzZSI+CiAgICAgIDxwYXRoIGQ9Ik0xNS41LDMwLjg2NGwtMTItN0ExLDEsMCwwLDEsMywyM1Y5YTEsMSwwLDAsMSwuNS0uODY0bDEyLTdhMSwxLDAsMCwxLDEuMDA4LDBsMTIsN0ExLDEsMCwwLDEsMjksOVYyM0gyN1Y5LjU3NEwxNiwzLjE1OCw1LDkuNTc0VjIyLjQyNmwxMS41LDYuNzFaIiBmaWxsPSIjZmZmIi8+CiAgICAgIDxyZWN0IHg9IjIiIHk9IjIyIiB3aWR0aD0iMTUiIGhlaWdodD0iMTAiIGZpbGw9InVybCgjYjM3M2Q5MTYtMzVkMy00ODQwLTliOTYtYzFhYTc5MjUyODc2KSIvPgogICAgICA8cGF0aCBkPSJNMjEsMjUuNWgydi05YTEsMSwwLDAsMC0uNS0uODY0bC02LTMuNWExLDEsMCwwLDAtMS4wMDgsMGwtNiwzLjVBMSwxLDAsMCwwLDksMTYuNVYyMWgyVjE3LjA3NGw1LTIuOTE2LDUsMi45MTZaIiBmaWxsPSIjZmZmIi8+CiAgICAgIDxyZWN0IHg9IjE5IiB5PSIxOCIgd2lkdGg9IjUiIGhlaWdodD0iOSIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNDMgNDUpIHJvdGF0ZSgxODApIiBmaWxsPSJ1cmwoI2Y2ZmI0ODA4LTA3Y2EtNDdkZS1iOTY2LWI5M2U0OGFkMDRmYSkiLz4KICAgIDwvbWFzaz4KICAgIDxsaW5lYXJHcmFkaWVudCBpZD0iYWY4YWM3NjAtNzY5YS00MDc4LWI2ZmUtYTlmOGRjMzU3OThjIiB5MT0iMzIiIHgyPSIzMiIgZ3JhZGllbnRVbml0cz0idXNlclNwYWNlT25Vc2UiPgogICAgICA8c3RvcCBvZmZzZXQ9IjAuMSIgc3RvcC1jb2xvcj0iIzQyYmU2NSIvPgogICAgICA8c3RvcCBvZmZzZXQ9IjAuOSIgc3RvcC1jb2xvcj0iIzAwN2Q3OSIvPgogICAgPC9saW5lYXJHcmFkaWVudD4KICA8L2RlZnM+CiAgPGcgaWQ9ImI0ODI0ZTUxLWRmMWMtNDdmMS1iMTc4LTQzZjYyOTUwYmJiNSIgZGF0YS1uYW1lPSJMYXllciAyIj4KICAgIDxnIGlkPSJiZjg4ZTFmMy1hYWFiLTRjNWEtYWVlYi02NDU2OTJiYWMxY2UiIGRhdGEtbmFtZT0iTGlnaHQgdGhlbWUgaWNvbnMiPgogICAgICA8Zz4KICAgICAgICA8ZyBtYXNrPSJ1cmwoI2FmODM2MWFjLTljYzctNGY3Yi1iMTEyLTAzZDdkN2E5MTQ1NCkiPgogICAgICAgICAgPHJlY3Qgd2lkdGg9IjMyIiBoZWlnaHQ9IjMyIiBmaWxsPSJ1cmwoI2FmOGFjNzYwLTc2OWEtNDA3OC1iNmZlLWE5ZjhkYzM1Nzk4YykiLz4KICAgICAgICA8L2c+CiAgICAgICAgPHBhdGggZD0iTTE2LDMxYTEsMSwwLDAsMS0uNS0uMTM2bC0zLTEuNzVhMSwxLDAsMCwxLS41LS44NjR2LTMuNWExLDEsMCwwLDEsLjUtLjg2NGwzLTEuNzVhMSwxLDAsMCwxLDEuMDA4LDBsMywxLjc1YTEsMSwwLDAsMSwuNS44NjR2My41YTEsMSwwLDAsMS0uNS44NjRsLTMsMS43NUExLDEsMCwwLDEsMTYsMzFabS0yLTMuMzI0LDIsMS4xNjYsMi0xLjE2NlYyNS4zMjRsLTItMS4xNjYtMiwxLjE2NloiIGZpbGw9IiMwMDFkNmMiLz4KICAgICAgPC9nPgogICAgPC9nPgogIDwvZz4KPC9zdmc+Cg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - IBM
  - GPFS
  - IBM Storage Scale
  - CSI Driver
  labels:
    operator: ibm-spectrum-scale-csi-operator
  links:
  - name: IBM Storage Scale CSI Documentation
    url: https://www.ibm.com/docs/en/spectrum-scale-csi
  - name: CSI Developer Documentation
    url: https://kubernetes-csi.github.io/docs/
  maintainers:
  - email: madhu.punjabi@in.ibm.com
    name: Madhu Thorat
  - email: amdabhad@in.ibm.com
    name: Amol Dabhade
  - email: Nitish.Kumar4@ibm.com
    name: Nitish Kumar
  maturity: alpha
  provider:
    name: IBM
  replaces: ibm-spectrum-scale-csi-operator.v2.5.1
  version: 0.0.0
