resources:
  metadata:
    displayDescription: "Represents a deployment of the IBM CSI Spectrum Scale driver."
    displayName: "IBM CSI Spectrum Scale Driver Setup"
    name: "ibmCSIScaleOperatorSetup"
    description: "Represents a deployment of the IBM CSI Spectrum Scale driver."
  resourceDefs:
    containerImages:
    - metadata:
        name: ibm_spectrum_scale_csi_operator
      image: cpopen/ibm-spectrum-scale-csi-operator
      tag: v2.10.0
      digest: sha256:da7ada19c06b20edc9b3c8067a8380f6879899022dda8a5c1cbed7c15b2a381d
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:36f410d228bd5329444ed82e17ad996103f166aad58db2a17b4fa5ce2601db15
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: amd64
          os: linux
        tag: v2.10.0-amd64
      - digest: sha256:5e9ae31d0be1fc843da44ddd85c3ac5540ef3d54ee50952f4fff99a7cf6e0478
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: ppc64le
          os: linux
        tag: v2.10.0-ppc64le
      - digest: sha256:ead53b0e0514b55735d9fb1aeb26925f9dbd0700c2ece4ee6d83d09118818518
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: s390x
          os: linux
        tag: v2.10.0-s390x
    files:
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/crds/csi_v1_csiscaleoperator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/operator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/service_account.yaml
