resources:
  metadata:
    displayDescription: "Represents a deployment of the IBM CSI Spectrum Scale driver."
    displayName: "IBM CSI Spectrum Scale Driver Setup"
    name: "ibmCSIScaleOperatorSetup"
    description: "Represents a deployment of the IBM CSI Spectrum Scale driver."
  resourceDefs:
    containerImages:
    - metadata:
        name: ibm_spectrum_scale_csi_operator
      image: cpopen/ibm-spectrum-scale-csi-operator
      tag: v2.4.0
      digest: sha256:4800e1ee33d575cc653d5c69f3c387f0cca10ae71f33930d3a9c7d3341d7728d  
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:7ac891c5dd57b3fe9f155555fd7eb6f56a9e482948e78da9c0112982aad21353
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: amd64
          os: linux
        tag: v2.4.0-amd64
      - digest: sha256:7631d6c3ce65c6773cfec851cb02ed708521a3587b92dc570bc96feea18f8fa5 
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: ppc64le
          os: linux
        tag: v2.4.0-ppc64le
      - digest: sha256:4bf05cbc9102cab1a5f7113cde67567dd24c2ce9c8cf6088b08d00d665f88e2a
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: s390x
          os: linux
        tag: v2.4.0-s390x
    files:
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/crds/csi_v1_csiscaleoperator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/operator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/service_account.yaml
