resources:
  metadata:
    displayDescription: "Represents a deployment of the IBM CSI Spectrum Scale driver."
    displayName: "IBM CSI Spectrum Scale Driver Setup"
    name: "ibmCSIScaleOperatorSetup"
    description: "Represents a deployment of the IBM CSI Spectrum Scale driver."
  resourceDefs:
    containerImages:
    - metadata:
        name: ibm_spectrum_scale_csi_operator
      image: cpopen/ibm-spectrum-scale-csi-operator
      tag: v2.5.0
      digest: sha256:38751e2b7a4624e588747ed427c2c2146bee320bab74b0bb288f38c2c5d2bddd  
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:66c6200c6ffa8b9ead74ea5c277f2bd4cea2a56edc7b792d81813dc000fce804
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: amd64
          os: linux
        tag: v2.5.0-amd64
      - digest: sha256:cdd86446cf91b5903fa33cf487a9e56134e415019ba0e5ea79f58d0956c0873a 
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: ppc64le
          os: linux
        tag: v2.5.0-ppc64le
      - digest: sha256:0c9071699bcc5aa034c772ed420723b831eef13e136bad93f1396cf3e1256615
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: s390x
          os: linux
        tag: v2.5.0-s390x
    files:
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/crds/csi_v1_csiscaleoperator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/operator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/service_account.yaml
