resources:
  metadata:
    displayDescription: "Represents a deployment of the IBM CSI Spectrum Scale driver."
    displayName: "IBM CSI Spectrum Scale Driver Setup"
    name: "ibmCSIScaleOperatorSetup"
    description: "Represents a deployment of the IBM CSI Spectrum Scale driver."
  resourceDefs:
    files:
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: deploy/crds/csiscaleoperators.csi.ibm.com.crd.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: deploy/operator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: deploy/role_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: deploy/role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: deploy/service_account.yaml
    - mediaType: application/vnd.case.resource.image.manifest.v1
      ref: manifest.yaml
