resources:
  metadata:
    displayDescription: "Represents a deployment of the IBM CSI Spectrum Scale driver."
    displayName: "IBM CSI Spectrum Scale Driver Setup"
    name: "ibmCSIScaleOperatorSetup"
    description: "Represents a deployment of the IBM CSI Spectrum Scale driver."
  resourceDefs:
    containerImages:
    - metadata:
        name: ibm_spectrum_scale_csi_operator
      image: cpopen/ibm-spectrum-scale-csi-operator
      tag: v2.6.0
      digest: sha256:6eecb931bac6a9d6ae16a522ee30225fbbeca77a32a108b696c91d02c5ac87e1
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:b5402b0bdb7b1d81f0d20286b8d138cf1f309bac987eb8abb5786474c243a757
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: amd64
          os: linux
        tag: v2.6.0-amd64
      - digest: sha256:cdec46b8aab3e415ca0b865c4ac42a3d57c6a2db65235d74d53d9bb6d2550e74
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: ppc64le
          os: linux
        tag: v2.6.0-ppc64le
      - digest: sha256:24fdf0e5d8340b0c71a654ed53b834b4b7401dd589c9389d90cd40badbf3793c
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: s390x
          os: linux
        tag: v2.6.0-s390x
    files:
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/crds/csi_v1_csiscaleoperator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/operator.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: cluster/deploy/service_account.yaml
