---
- name: Remove old version of secret
  k8s:
    state: absent
    definition:
      apiVersion: "v1"
      kind: "Secret"
      metadata:
        name: "{{item.metadata.name}}"

- name: Ensure the secret has been created with the correct label
  k8s:
    state: present
    definition:
      apiVersion: "v1"
      kind: "Secret"
      metadata:
        name: "{{item.metadata.name}}"
        namespace: "{{meta.namespace}}"
        labels:
          app.kubernetes.io/name: "ibm-spectrum-scale-csi-operator"
      data: "{{item.data}}"
      type: "{{item.type}}"
