---
- name: Process Secret
  become: no
  hosts: all
  gather_facts: false
  vars:
    LABEL: app.kubernetes.io/name
    LABEL_VALUE: ibm-spectrum-scale-csi-operator
    ANSIBLE_JINJA2_NATIVE: 1
  tasks:
    - name: Verify this is a labeled secret.
      meta: end_play
      when: __secret.metadata.labels is not defined  or
        __secret.metadata.labels["app.kubernetes.io/name"] is not defined or
        __secret.metadata.labels["app.kubernetes.io/name"]  != "ibm-spectrum-scale-csi-operator"

    - name: Get Scale operators in namespace
      k8s_info:
        kind: CSIScaleOperator
        namespace: "{{ __secret.metadata.namespace }}"
      register: results

    - name: Bump the trigger for resources with the secret.
      k8s:
        state: present
        definition:
          apiVersion: "{{item.apiVersion}}"
          kind: "CSIScaleOperator"
          metadata:
            name: "{{item.metadata.name}}"
            namespace: "{{meta.namespace}}"
          spec:
            trigger: "{{(item.spec.trigger  |  default(0) | int ) + 1 | int }}"
      when: "__secret.metadata.name in (item | json_query('spec.clusters[*].secrets') )"
      loop: "{{results.resources}}"
