apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

commonAnnotations:
  productVersion: 2.5.0
images:
- name: csi-operator
  newName: quay.io/ibm-spectrum-scale/ibm-spectrum-scale-csi-operator
  newTag: v2.5.0
