---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ibm-spectrum-scale-csi-driver

resources:
- ../../rbac/
- ../../manager/
- ../../crd/

patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=ibm-spectrum-scale-csi-operator"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ibm-spectrum-scale-csi-operator
      spec:
        template:
          spec:
            containers:
              - name: operator
                image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:ff4a8b6a64439889d28e94c50f165c255abc67c17efa44798c76d41a6ecbd9fa
                env:
                  - name: METRICS_BIND_ADDRESS
                  - name: WATCH_NAMESPACE
                  - name: CSI_DRIVER_IMAGE
                    value: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:75dd2f238268b7f2e855ed9e9a8ae356a34bb9cc3e996f81cba20d363830a2f5
