---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ibm-spectrum-scale-csi-driver

resources:
- ../../rbac/
- ../../manager/
- ../../crd/

patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=ibm-spectrum-scale-csi-operator"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ibm-spectrum-scale-csi-operator
      spec:
        template:
          spec:
            containers:
              - name: operator
                image: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-operator@sha256:2215afd085df67c4726d52fd8ef35e962501f7c0ea469aa97a81b388f1944dc6
                env:
                  - name: METRICS_BIND_ADDRESS
                  - name: WATCH_NAMESPACE
                  - name: CSI_DRIVER_IMAGE
                    value: quay.io/ibm-spectrum-scale-dev/ibm-spectrum-scale-csi-driver@sha256:b26e4129ac9e71ee9f9e4a12d91b85812262a85516cf79646c105bedfa650485
