apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: ns1
  labels:
    app: nginx
spec:
  containers:
   - name: web-server
     image: gcr.io/google-containers/nginx
     volumeMounts:
       - name: mypvc
         mountPath: /data
     ports:
     - containerPort: 80
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: cache-s3-pvc1
