# Create a secret with s3 bucket details first.
# e.g. for a PVC with name 'cache-s3-pvc1' in namespace 'ns1',
# oc create secret generic cache-s3-pvc1-secret -n ns1 \
# --from-literal=endpoint=<end_point> --from-literal=bucket=<bucket_name> \
# --from-literal=accesskey=<access_key> --from-literal=secretkey=<secret_key>
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cache-s3-pvc1
  namespace: ns1
spec:
  storageClassName: ibm-scale-cache-s3
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
