apiVersion: v1
kind: PersistentVolume
metadata:
        name: static-scale-static-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  csi:
    driver: spectrumscale.csi.ibm.com
    volumeHandle: "7118073361626808055;09762E69:5D36FE8D;path=/ibm/gpfs0/staticdir"

