// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuthenticationKeyPostv2Params creates a new AuthenticationKeyPostv2Params object
// with the default values initialized.
func NewAuthenticationKeyPostv2Params() *AuthenticationKeyPostv2Params {

	return &AuthenticationKeyPostv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewAuthenticationKeyPostv2ParamsWithTimeout creates a new AuthenticationKeyPostv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewAuthenticationKeyPostv2ParamsWithTimeout(timeout time.Duration) *AuthenticationKeyPostv2Params {

	return &AuthenticationKeyPostv2Params{

		timeout: timeout,
	}
}

// NewAuthenticationKeyPostv2ParamsWithContext creates a new AuthenticationKeyPostv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewAuthenticationKeyPostv2ParamsWithContext(ctx context.Context) *AuthenticationKeyPostv2Params {

	return &AuthenticationKeyPostv2Params{

		Context: ctx,
	}
}

// NewAuthenticationKeyPostv2ParamsWithHTTPClient creates a new AuthenticationKeyPostv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAuthenticationKeyPostv2ParamsWithHTTPClient(client *http.Client) *AuthenticationKeyPostv2Params {

	return &AuthenticationKeyPostv2Params{
		HTTPClient: client,
	}
}

/*AuthenticationKeyPostv2Params contains all the parameters to send to the API endpoint
for the authentication key postv2 operation typically these are written to a http.Request
*/
type AuthenticationKeyPostv2Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the authentication key postv2 params
func (o *AuthenticationKeyPostv2Params) WithTimeout(timeout time.Duration) *AuthenticationKeyPostv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the authentication key postv2 params
func (o *AuthenticationKeyPostv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the authentication key postv2 params
func (o *AuthenticationKeyPostv2Params) WithContext(ctx context.Context) *AuthenticationKeyPostv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the authentication key postv2 params
func (o *AuthenticationKeyPostv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the authentication key postv2 params
func (o *AuthenticationKeyPostv2Params) WithHTTPClient(client *http.Client) *AuthenticationKeyPostv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the authentication key postv2 params
func (o *AuthenticationKeyPostv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AuthenticationKeyPostv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
