// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCallhomeGetParams creates a new CallhomeGetParams object
// with the default values initialized.
func NewCallhomeGetParams() *CallhomeGetParams {

	return &CallhomeGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCallhomeGetParamsWithTimeout creates a new CallhomeGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCallhomeGetParamsWithTimeout(timeout time.Duration) *CallhomeGetParams {

	return &CallhomeGetParams{

		timeout: timeout,
	}
}

// NewCallhomeGetParamsWithContext creates a new CallhomeGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewCallhomeGetParamsWithContext(ctx context.Context) *CallhomeGetParams {

	return &CallhomeGetParams{

		Context: ctx,
	}
}

// NewCallhomeGetParamsWithHTTPClient creates a new CallhomeGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCallhomeGetParamsWithHTTPClient(client *http.Client) *CallhomeGetParams {

	return &CallhomeGetParams{
		HTTPClient: client,
	}
}

/*CallhomeGetParams contains all the parameters to send to the API endpoint
for the callhome get operation typically these are written to a http.Request
*/
type CallhomeGetParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the callhome get params
func (o *CallhomeGetParams) WithTimeout(timeout time.Duration) *CallhomeGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the callhome get params
func (o *CallhomeGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the callhome get params
func (o *CallhomeGetParams) WithContext(ctx context.Context) *CallhomeGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the callhome get params
func (o *CallhomeGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the callhome get params
func (o *CallhomeGetParams) WithHTTPClient(client *http.Client) *CallhomeGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the callhome get params
func (o *CallhomeGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CallhomeGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
