// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewClusterJobsDeletev2Params creates a new ClusterJobsDeletev2Params object
// with the default values initialized.
func NewClusterJobsDeletev2Params() *ClusterJobsDeletev2Params {
	var ()
	return &ClusterJobsDeletev2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewClusterJobsDeletev2ParamsWithTimeout creates a new ClusterJobsDeletev2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewClusterJobsDeletev2ParamsWithTimeout(timeout time.Duration) *ClusterJobsDeletev2Params {
	var ()
	return &ClusterJobsDeletev2Params{

		timeout: timeout,
	}
}

// NewClusterJobsDeletev2ParamsWithContext creates a new ClusterJobsDeletev2Params object
// with the default values initialized, and the ability to set a context for a request
func NewClusterJobsDeletev2ParamsWithContext(ctx context.Context) *ClusterJobsDeletev2Params {
	var ()
	return &ClusterJobsDeletev2Params{

		Context: ctx,
	}
}

// NewClusterJobsDeletev2ParamsWithHTTPClient creates a new ClusterJobsDeletev2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewClusterJobsDeletev2ParamsWithHTTPClient(client *http.Client) *ClusterJobsDeletev2Params {
	var ()
	return &ClusterJobsDeletev2Params{
		HTTPClient: client,
	}
}

/*ClusterJobsDeletev2Params contains all the parameters to send to the API endpoint
for the cluster jobs deletev2 operation typically these are written to a http.Request
*/
type ClusterJobsDeletev2Params struct {

	/*JobID*/
	JobID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) WithTimeout(timeout time.Duration) *ClusterJobsDeletev2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) WithContext(ctx context.Context) *ClusterJobsDeletev2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) WithHTTPClient(client *http.Client) *ClusterJobsDeletev2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithJobID adds the jobID to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) WithJobID(jobID string) *ClusterJobsDeletev2Params {
	o.SetJobID(jobID)
	return o
}

// SetJobID adds the jobId to the cluster jobs deletev2 params
func (o *ClusterJobsDeletev2Params) SetJobID(jobID string) {
	o.JobID = jobID
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterJobsDeletev2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param jobId
	if err := r.SetPathParam("jobId", o.JobID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
