// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewClusterJobsGetv20Params creates a new ClusterJobsGetv20Params object
// with the default values initialized.
func NewClusterJobsGetv20Params() *ClusterJobsGetv20Params {
	var ()
	return &ClusterJobsGetv20Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewClusterJobsGetv20ParamsWithTimeout creates a new ClusterJobsGetv20Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewClusterJobsGetv20ParamsWithTimeout(timeout time.Duration) *ClusterJobsGetv20Params {
	var ()
	return &ClusterJobsGetv20Params{

		timeout: timeout,
	}
}

// NewClusterJobsGetv20ParamsWithContext creates a new ClusterJobsGetv20Params object
// with the default values initialized, and the ability to set a context for a request
func NewClusterJobsGetv20ParamsWithContext(ctx context.Context) *ClusterJobsGetv20Params {
	var ()
	return &ClusterJobsGetv20Params{

		Context: ctx,
	}
}

// NewClusterJobsGetv20ParamsWithHTTPClient creates a new ClusterJobsGetv20Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewClusterJobsGetv20ParamsWithHTTPClient(client *http.Client) *ClusterJobsGetv20Params {
	var ()
	return &ClusterJobsGetv20Params{
		HTTPClient: client,
	}
}

/*ClusterJobsGetv20Params contains all the parameters to send to the API endpoint
for the cluster jobs getv2 0 operation typically these are written to a http.Request
*/
type ClusterJobsGetv20Params struct {

	/*Fields
	  Comma separated list of fields to be included in response. '\_all\_' selects all available fields.

	*/
	Fields *string
	/*JobID*/
	JobID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) WithTimeout(timeout time.Duration) *ClusterJobsGetv20Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) WithContext(ctx context.Context) *ClusterJobsGetv20Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) WithHTTPClient(client *http.Client) *ClusterJobsGetv20Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) WithFields(fields *string) *ClusterJobsGetv20Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithJobID adds the jobID to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) WithJobID(jobID string) *ClusterJobsGetv20Params {
	o.SetJobID(jobID)
	return o
}

// SetJobID adds the jobId to the cluster jobs getv2 0 params
func (o *ClusterJobsGetv20Params) SetJobID(jobID string) {
	o.JobID = jobID
}

// WriteToRequest writes these params to a swagger request
func (o *ClusterJobsGetv20Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param jobId
	if err := r.SetPathParam("jobId", o.JobID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
