// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// ConfigGetv2Reader is a Reader for the ConfigGetv2 structure.
type ConfigGetv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfigGetv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewConfigGetv2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewConfigGetv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewConfigGetv2OK creates a ConfigGetv2OK with default headers values
func NewConfigGetv2OK() *ConfigGetv2OK {
	return &ConfigGetv2OK{}
}

/*ConfigGetv2OK handles this case with default header values.

successful operation
*/
type ConfigGetv2OK struct {
	Payload *models.ConfigInlineResponse200
}

func (o *ConfigGetv2OK) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/config][%d] configGetv2OK  %+v", 200, o.Payload)
}

func (o *ConfigGetv2OK) GetPayload() *models.ConfigInlineResponse200 {
	return o.Payload
}

func (o *ConfigGetv2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ConfigInlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewConfigGetv2InternalServerError creates a ConfigGetv2InternalServerError with default headers values
func NewConfigGetv2InternalServerError() *ConfigGetv2InternalServerError {
	return &ConfigGetv2InternalServerError{}
}

/*ConfigGetv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type ConfigGetv2InternalServerError struct {
	Payload *models.Http400BadRequest
}

func (o *ConfigGetv2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/config][%d] configGetv2InternalServerError  %+v", 500, o.Payload)
}

func (o *ConfigGetv2InternalServerError) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *ConfigGetv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
