// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteBucketKeysv2Params creates a new DeleteBucketKeysv2Params object
// with the default values initialized.
func NewDeleteBucketKeysv2Params() *DeleteBucketKeysv2Params {
	var ()
	return &DeleteBucketKeysv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteBucketKeysv2ParamsWithTimeout creates a new DeleteBucketKeysv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteBucketKeysv2ParamsWithTimeout(timeout time.Duration) *DeleteBucketKeysv2Params {
	var ()
	return &DeleteBucketKeysv2Params{

		timeout: timeout,
	}
}

// NewDeleteBucketKeysv2ParamsWithContext creates a new DeleteBucketKeysv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteBucketKeysv2ParamsWithContext(ctx context.Context) *DeleteBucketKeysv2Params {
	var ()
	return &DeleteBucketKeysv2Params{

		Context: ctx,
	}
}

// NewDeleteBucketKeysv2ParamsWithHTTPClient creates a new DeleteBucketKeysv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteBucketKeysv2ParamsWithHTTPClient(client *http.Client) *DeleteBucketKeysv2Params {
	var ()
	return &DeleteBucketKeysv2Params{
		HTTPClient: client,
	}
}

/*DeleteBucketKeysv2Params contains all the parameters to send to the API endpoint
for the delete bucket keysv2 operation typically these are written to a http.Request
*/
type DeleteBucketKeysv2Params struct {

	/*BucketName
	  Bucket name

	*/
	BucketName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) WithTimeout(timeout time.Duration) *DeleteBucketKeysv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) WithContext(ctx context.Context) *DeleteBucketKeysv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) WithHTTPClient(client *http.Client) *DeleteBucketKeysv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBucketName adds the bucketName to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) WithBucketName(bucketName string) *DeleteBucketKeysv2Params {
	o.SetBucketName(bucketName)
	return o
}

// SetBucketName adds the bucketName to the delete bucket keysv2 params
func (o *DeleteBucketKeysv2Params) SetBucketName(bucketName string) {
	o.BucketName = bucketName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteBucketKeysv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param bucketName
	if err := r.SetPathParam("bucketName", o.BucketName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
