// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// DeleteBucketKeysv2Reader is a Reader for the DeleteBucketKeysv2 structure.
type DeleteBucketKeysv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteBucketKeysv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteBucketKeysv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteBucketKeysv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteBucketKeysv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteBucketKeysv2Accepted creates a DeleteBucketKeysv2Accepted with default headers values
func NewDeleteBucketKeysv2Accepted() *DeleteBucketKeysv2Accepted {
	return &DeleteBucketKeysv2Accepted{}
}

/*DeleteBucketKeysv2Accepted handles this case with default header values.

successful operation
*/
type DeleteBucketKeysv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *DeleteBucketKeysv2Accepted) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/bucket/keys/{bucketName}][%d] deleteBucketKeysv2Accepted  %+v", 202, o.Payload)
}

func (o *DeleteBucketKeysv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *DeleteBucketKeysv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBucketKeysv2BadRequest creates a DeleteBucketKeysv2BadRequest with default headers values
func NewDeleteBucketKeysv2BadRequest() *DeleteBucketKeysv2BadRequest {
	return &DeleteBucketKeysv2BadRequest{}
}

/*DeleteBucketKeysv2BadRequest handles this case with default header values.

Invalid request
*/
type DeleteBucketKeysv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *DeleteBucketKeysv2BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/bucket/keys/{bucketName}][%d] deleteBucketKeysv2BadRequest  %+v", 400, o.Payload)
}

func (o *DeleteBucketKeysv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *DeleteBucketKeysv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteBucketKeysv2InternalServerError creates a DeleteBucketKeysv2InternalServerError with default headers values
func NewDeleteBucketKeysv2InternalServerError() *DeleteBucketKeysv2InternalServerError {
	return &DeleteBucketKeysv2InternalServerError{}
}

/*DeleteBucketKeysv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type DeleteBucketKeysv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *DeleteBucketKeysv2InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/bucket/keys/{bucketName}][%d] deleteBucketKeysv2InternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteBucketKeysv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *DeleteBucketKeysv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
