// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// DirectoryDeletev20Reader is a Reader for the DirectoryDeletev20 structure.
type DirectoryDeletev20Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DirectoryDeletev20Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDirectoryDeletev20Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDirectoryDeletev20BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDirectoryDeletev20InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDirectoryDeletev20Accepted creates a DirectoryDeletev20Accepted with default headers values
func NewDirectoryDeletev20Accepted() *DirectoryDeletev20Accepted {
	return &DirectoryDeletev20Accepted{}
}

/*DirectoryDeletev20Accepted handles this case with default header values.

successful operation
*/
type DirectoryDeletev20Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *DirectoryDeletev20Accepted) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/directory/{path}][%d] directoryDeletev20Accepted  %+v", 202, o.Payload)
}

func (o *DirectoryDeletev20Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *DirectoryDeletev20Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectoryDeletev20BadRequest creates a DirectoryDeletev20BadRequest with default headers values
func NewDirectoryDeletev20BadRequest() *DirectoryDeletev20BadRequest {
	return &DirectoryDeletev20BadRequest{}
}

/*DirectoryDeletev20BadRequest handles this case with default header values.

Invalid file system, fileset or path
*/
type DirectoryDeletev20BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *DirectoryDeletev20BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/directory/{path}][%d] directoryDeletev20BadRequest  %+v", 400, o.Payload)
}

func (o *DirectoryDeletev20BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *DirectoryDeletev20BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDirectoryDeletev20InternalServerError creates a DirectoryDeletev20InternalServerError with default headers values
func NewDirectoryDeletev20InternalServerError() *DirectoryDeletev20InternalServerError {
	return &DirectoryDeletev20InternalServerError{}
}

/*DirectoryDeletev20InternalServerError handles this case with default header values.

An unexpected error occurred.
*/
type DirectoryDeletev20InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *DirectoryDeletev20InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/directory/{path}][%d] directoryDeletev20InternalServerError  %+v", 500, o.Payload)
}

func (o *DirectoryDeletev20InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *DirectoryDeletev20InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
