// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NewDirectoryPostv20Params creates a new DirectoryPostv20Params object
// with the default values initialized.
func NewDirectoryPostv20Params() *DirectoryPostv20Params {
	var ()
	return &DirectoryPostv20Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewDirectoryPostv20ParamsWithTimeout creates a new DirectoryPostv20Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewDirectoryPostv20ParamsWithTimeout(timeout time.Duration) *DirectoryPostv20Params {
	var ()
	return &DirectoryPostv20Params{

		timeout: timeout,
	}
}

// NewDirectoryPostv20ParamsWithContext creates a new DirectoryPostv20Params object
// with the default values initialized, and the ability to set a context for a request
func NewDirectoryPostv20ParamsWithContext(ctx context.Context) *DirectoryPostv20Params {
	var ()
	return &DirectoryPostv20Params{

		Context: ctx,
	}
}

// NewDirectoryPostv20ParamsWithHTTPClient creates a new DirectoryPostv20Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDirectoryPostv20ParamsWithHTTPClient(client *http.Client) *DirectoryPostv20Params {
	var ()
	return &DirectoryPostv20Params{
		HTTPClient: client,
	}
}

/*DirectoryPostv20Params contains all the parameters to send to the API endpoint
for the directory postv2 0 operation typically these are written to a http.Request
*/
type DirectoryPostv20Params struct {

	/*Body*/
	Body *models.FileOwner
	/*FilesetName
	  The fileset name

	*/
	FilesetName string
	/*FilesystemName
	  The name of the file system

	*/
	FilesystemName string
	/*Path
	  The directory path relative to the fileset path

	*/
	Path string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the directory postv2 0 params
func (o *DirectoryPostv20Params) WithTimeout(timeout time.Duration) *DirectoryPostv20Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the directory postv2 0 params
func (o *DirectoryPostv20Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the directory postv2 0 params
func (o *DirectoryPostv20Params) WithContext(ctx context.Context) *DirectoryPostv20Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the directory postv2 0 params
func (o *DirectoryPostv20Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the directory postv2 0 params
func (o *DirectoryPostv20Params) WithHTTPClient(client *http.Client) *DirectoryPostv20Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the directory postv2 0 params
func (o *DirectoryPostv20Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the directory postv2 0 params
func (o *DirectoryPostv20Params) WithBody(body *models.FileOwner) *DirectoryPostv20Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the directory postv2 0 params
func (o *DirectoryPostv20Params) SetBody(body *models.FileOwner) {
	o.Body = body
}

// WithFilesetName adds the filesetName to the directory postv2 0 params
func (o *DirectoryPostv20Params) WithFilesetName(filesetName string) *DirectoryPostv20Params {
	o.SetFilesetName(filesetName)
	return o
}

// SetFilesetName adds the filesetName to the directory postv2 0 params
func (o *DirectoryPostv20Params) SetFilesetName(filesetName string) {
	o.FilesetName = filesetName
}

// WithFilesystemName adds the filesystemName to the directory postv2 0 params
func (o *DirectoryPostv20Params) WithFilesystemName(filesystemName string) *DirectoryPostv20Params {
	o.SetFilesystemName(filesystemName)
	return o
}

// SetFilesystemName adds the filesystemName to the directory postv2 0 params
func (o *DirectoryPostv20Params) SetFilesystemName(filesystemName string) {
	o.FilesystemName = filesystemName
}

// WithPath adds the path to the directory postv2 0 params
func (o *DirectoryPostv20Params) WithPath(path string) *DirectoryPostv20Params {
	o.SetPath(path)
	return o
}

// SetPath adds the path to the directory postv2 0 params
func (o *DirectoryPostv20Params) SetPath(path string) {
	o.Path = path
}

// WriteToRequest writes these params to a swagger request
func (o *DirectoryPostv20Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param filesetName
	if err := r.SetPathParam("filesetName", o.FilesetName); err != nil {
		return err
	}

	// path param filesystemName
	if err := r.SetPathParam("filesystemName", o.FilesystemName); err != nil {
		return err
	}

	// path param path
	if err := r.SetPathParam("path", o.Path); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
