// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NewEnableDisableQuotaDefaultsPutv20Params creates a new EnableDisableQuotaDefaultsPutv20Params object
// with the default values initialized.
func NewEnableDisableQuotaDefaultsPutv20Params() *EnableDisableQuotaDefaultsPutv20Params {
	var ()
	return &EnableDisableQuotaDefaultsPutv20Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewEnableDisableQuotaDefaultsPutv20ParamsWithTimeout creates a new EnableDisableQuotaDefaultsPutv20Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewEnableDisableQuotaDefaultsPutv20ParamsWithTimeout(timeout time.Duration) *EnableDisableQuotaDefaultsPutv20Params {
	var ()
	return &EnableDisableQuotaDefaultsPutv20Params{

		timeout: timeout,
	}
}

// NewEnableDisableQuotaDefaultsPutv20ParamsWithContext creates a new EnableDisableQuotaDefaultsPutv20Params object
// with the default values initialized, and the ability to set a context for a request
func NewEnableDisableQuotaDefaultsPutv20ParamsWithContext(ctx context.Context) *EnableDisableQuotaDefaultsPutv20Params {
	var ()
	return &EnableDisableQuotaDefaultsPutv20Params{

		Context: ctx,
	}
}

// NewEnableDisableQuotaDefaultsPutv20ParamsWithHTTPClient creates a new EnableDisableQuotaDefaultsPutv20Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEnableDisableQuotaDefaultsPutv20ParamsWithHTTPClient(client *http.Client) *EnableDisableQuotaDefaultsPutv20Params {
	var ()
	return &EnableDisableQuotaDefaultsPutv20Params{
		HTTPClient: client,
	}
}

/*EnableDisableQuotaDefaultsPutv20Params contains all the parameters to send to the API endpoint
for the enable disable quota defaults putv2 0 operation typically these are written to a http.Request
*/
type EnableDisableQuotaDefaultsPutv20Params struct {

	/*Body*/
	Body *models.QuotaDefaultsFsetConfig
	/*FilesetName
	  The fileset name

	*/
	FilesetName string
	/*FilesystemName
	  The filesystem name, :all:, :all\_local: or :all\_remote:

	*/
	FilesystemName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) WithTimeout(timeout time.Duration) *EnableDisableQuotaDefaultsPutv20Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) WithContext(ctx context.Context) *EnableDisableQuotaDefaultsPutv20Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) WithHTTPClient(client *http.Client) *EnableDisableQuotaDefaultsPutv20Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) WithBody(body *models.QuotaDefaultsFsetConfig) *EnableDisableQuotaDefaultsPutv20Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) SetBody(body *models.QuotaDefaultsFsetConfig) {
	o.Body = body
}

// WithFilesetName adds the filesetName to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) WithFilesetName(filesetName string) *EnableDisableQuotaDefaultsPutv20Params {
	o.SetFilesetName(filesetName)
	return o
}

// SetFilesetName adds the filesetName to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) SetFilesetName(filesetName string) {
	o.FilesetName = filesetName
}

// WithFilesystemName adds the filesystemName to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) WithFilesystemName(filesystemName string) *EnableDisableQuotaDefaultsPutv20Params {
	o.SetFilesystemName(filesystemName)
	return o
}

// SetFilesystemName adds the filesystemName to the enable disable quota defaults putv2 0 params
func (o *EnableDisableQuotaDefaultsPutv20Params) SetFilesystemName(filesystemName string) {
	o.FilesystemName = filesystemName
}

// WriteToRequest writes these params to a swagger request
func (o *EnableDisableQuotaDefaultsPutv20Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param filesetName
	if err := r.SetPathParam("filesetName", o.FilesetName); err != nil {
		return err
	}

	// path param filesystemName
	if err := r.SetPathParam("filesystemName", o.FilesystemName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
