// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// EnableDisableFsWatchPutv2Reader is a Reader for the EnableDisableFsWatchPutv2 structure.
type EnableDisableFsWatchPutv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnableDisableFsWatchPutv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewEnableDisableFsWatchPutv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEnableDisableFsWatchPutv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEnableDisableFsWatchPutv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEnableDisableFsWatchPutv2Accepted creates a EnableDisableFsWatchPutv2Accepted with default headers values
func NewEnableDisableFsWatchPutv2Accepted() *EnableDisableFsWatchPutv2Accepted {
	return &EnableDisableFsWatchPutv2Accepted{}
}

/*EnableDisableFsWatchPutv2Accepted handles this case with default header values.

successful operation
*/
type EnableDisableFsWatchPutv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *EnableDisableFsWatchPutv2Accepted) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/watch][%d] enableDisableFsWatchPutv2Accepted  %+v", 202, o.Payload)
}

func (o *EnableDisableFsWatchPutv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *EnableDisableFsWatchPutv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableDisableFsWatchPutv2BadRequest creates a EnableDisableFsWatchPutv2BadRequest with default headers values
func NewEnableDisableFsWatchPutv2BadRequest() *EnableDisableFsWatchPutv2BadRequest {
	return &EnableDisableFsWatchPutv2BadRequest{}
}

/*EnableDisableFsWatchPutv2BadRequest handles this case with default header values.

Invalid request
*/
type EnableDisableFsWatchPutv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *EnableDisableFsWatchPutv2BadRequest) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/watch][%d] enableDisableFsWatchPutv2BadRequest  %+v", 400, o.Payload)
}

func (o *EnableDisableFsWatchPutv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *EnableDisableFsWatchPutv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableDisableFsWatchPutv2InternalServerError creates a EnableDisableFsWatchPutv2InternalServerError with default headers values
func NewEnableDisableFsWatchPutv2InternalServerError() *EnableDisableFsWatchPutv2InternalServerError {
	return &EnableDisableFsWatchPutv2InternalServerError{}
}

/*EnableDisableFsWatchPutv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type EnableDisableFsWatchPutv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *EnableDisableFsWatchPutv2InternalServerError) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/watch][%d] enableDisableFsWatchPutv2InternalServerError  %+v", 500, o.Payload)
}

func (o *EnableDisableFsWatchPutv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *EnableDisableFsWatchPutv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
