// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// EnableDisableQuotaDefaultsPutv20Reader is a Reader for the EnableDisableQuotaDefaultsPutv20 structure.
type EnableDisableQuotaDefaultsPutv20Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnableDisableQuotaDefaultsPutv20Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewEnableDisableQuotaDefaultsPutv20Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewEnableDisableQuotaDefaultsPutv20BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewEnableDisableQuotaDefaultsPutv20InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEnableDisableQuotaDefaultsPutv20Accepted creates a EnableDisableQuotaDefaultsPutv20Accepted with default headers values
func NewEnableDisableQuotaDefaultsPutv20Accepted() *EnableDisableQuotaDefaultsPutv20Accepted {
	return &EnableDisableQuotaDefaultsPutv20Accepted{}
}

/*EnableDisableQuotaDefaultsPutv20Accepted handles this case with default header values.

successful operation
*/
type EnableDisableQuotaDefaultsPutv20Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *EnableDisableQuotaDefaultsPutv20Accepted) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/quotadefaults][%d] enableDisableQuotaDefaultsPutv20Accepted  %+v", 202, o.Payload)
}

func (o *EnableDisableQuotaDefaultsPutv20Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *EnableDisableQuotaDefaultsPutv20Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableDisableQuotaDefaultsPutv20BadRequest creates a EnableDisableQuotaDefaultsPutv20BadRequest with default headers values
func NewEnableDisableQuotaDefaultsPutv20BadRequest() *EnableDisableQuotaDefaultsPutv20BadRequest {
	return &EnableDisableQuotaDefaultsPutv20BadRequest{}
}

/*EnableDisableQuotaDefaultsPutv20BadRequest handles this case with default header values.

Invalid request
*/
type EnableDisableQuotaDefaultsPutv20BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *EnableDisableQuotaDefaultsPutv20BadRequest) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/quotadefaults][%d] enableDisableQuotaDefaultsPutv20BadRequest  %+v", 400, o.Payload)
}

func (o *EnableDisableQuotaDefaultsPutv20BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *EnableDisableQuotaDefaultsPutv20BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableDisableQuotaDefaultsPutv20InternalServerError creates a EnableDisableQuotaDefaultsPutv20InternalServerError with default headers values
func NewEnableDisableQuotaDefaultsPutv20InternalServerError() *EnableDisableQuotaDefaultsPutv20InternalServerError {
	return &EnableDisableQuotaDefaultsPutv20InternalServerError{}
}

/*EnableDisableQuotaDefaultsPutv20InternalServerError handles this case with default header values.

Internal Server Error
*/
type EnableDisableQuotaDefaultsPutv20InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *EnableDisableQuotaDefaultsPutv20InternalServerError) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/quotadefaults][%d] enableDisableQuotaDefaultsPutv20InternalServerError  %+v", 500, o.Payload)
}

func (o *EnableDisableQuotaDefaultsPutv20InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *EnableDisableQuotaDefaultsPutv20InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
