// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NewEnableDisableFsWatchPutv20Params creates a new EnableDisableFsWatchPutv20Params object
// with the default values initialized.
func NewEnableDisableFsWatchPutv20Params() *EnableDisableFsWatchPutv20Params {
	var ()
	return &EnableDisableFsWatchPutv20Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewEnableDisableFsWatchPutv20ParamsWithTimeout creates a new EnableDisableFsWatchPutv20Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewEnableDisableFsWatchPutv20ParamsWithTimeout(timeout time.Duration) *EnableDisableFsWatchPutv20Params {
	var ()
	return &EnableDisableFsWatchPutv20Params{

		timeout: timeout,
	}
}

// NewEnableDisableFsWatchPutv20ParamsWithContext creates a new EnableDisableFsWatchPutv20Params object
// with the default values initialized, and the ability to set a context for a request
func NewEnableDisableFsWatchPutv20ParamsWithContext(ctx context.Context) *EnableDisableFsWatchPutv20Params {
	var ()
	return &EnableDisableFsWatchPutv20Params{

		Context: ctx,
	}
}

// NewEnableDisableFsWatchPutv20ParamsWithHTTPClient creates a new EnableDisableFsWatchPutv20Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewEnableDisableFsWatchPutv20ParamsWithHTTPClient(client *http.Client) *EnableDisableFsWatchPutv20Params {
	var ()
	return &EnableDisableFsWatchPutv20Params{
		HTTPClient: client,
	}
}

/*EnableDisableFsWatchPutv20Params contains all the parameters to send to the API endpoint
for the enable disable fs watch putv2 0 operation typically these are written to a http.Request
*/
type EnableDisableFsWatchPutv20Params struct {

	/*Body*/
	Body *models.WatchfolderOperation
	/*FilesystemName
	  The filesystem name

	*/
	FilesystemName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) WithTimeout(timeout time.Duration) *EnableDisableFsWatchPutv20Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) WithContext(ctx context.Context) *EnableDisableFsWatchPutv20Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) WithHTTPClient(client *http.Client) *EnableDisableFsWatchPutv20Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) WithBody(body *models.WatchfolderOperation) *EnableDisableFsWatchPutv20Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) SetBody(body *models.WatchfolderOperation) {
	o.Body = body
}

// WithFilesystemName adds the filesystemName to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) WithFilesystemName(filesystemName string) *EnableDisableFsWatchPutv20Params {
	o.SetFilesystemName(filesystemName)
	return o
}

// SetFilesystemName adds the filesystemName to the enable disable fs watch putv2 0 params
func (o *EnableDisableFsWatchPutv20Params) SetFilesystemName(filesystemName string) {
	o.FilesystemName = filesystemName
}

// WriteToRequest writes these params to a swagger request
func (o *EnableDisableFsWatchPutv20Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param filesystemName
	if err := r.SetPathParam("filesystemName", o.FilesystemName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
