// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// EvictReader is a Reader for the Evict structure.
type EvictReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EvictReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewEvictAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewEvictInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewEvictAccepted creates a EvictAccepted with default headers values
func NewEvictAccepted() *EvictAccepted {
	return &EvictAccepted{}
}

/*EvictAccepted handles this case with default header values.

successful operation
*/
type EvictAccepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *EvictAccepted) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/cos/evict][%d] evictAccepted  %+v", 202, o.Payload)
}

func (o *EvictAccepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *EvictAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEvictInternalServerError creates a EvictInternalServerError with default headers values
func NewEvictInternalServerError() *EvictInternalServerError {
	return &EvictInternalServerError{}
}

/*EvictInternalServerError handles this case with default header values.

Internal Server Error
*/
type EvictInternalServerError struct {
	Payload *models.RequestStatus
}

func (o *EvictInternalServerError) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/cos/evict][%d] evictInternalServerError  %+v", 500, o.Payload)
}

func (o *EvictInternalServerError) GetPayload() *models.RequestStatus {
	return o.Payload
}

func (o *EvictInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
