// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NewFilesetsFilesetNamePutv2Params creates a new FilesetsFilesetNamePutv2Params object
// with the default values initialized.
func NewFilesetsFilesetNamePutv2Params() *FilesetsFilesetNamePutv2Params {
	var ()
	return &FilesetsFilesetNamePutv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewFilesetsFilesetNamePutv2ParamsWithTimeout creates a new FilesetsFilesetNamePutv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewFilesetsFilesetNamePutv2ParamsWithTimeout(timeout time.Duration) *FilesetsFilesetNamePutv2Params {
	var ()
	return &FilesetsFilesetNamePutv2Params{

		timeout: timeout,
	}
}

// NewFilesetsFilesetNamePutv2ParamsWithContext creates a new FilesetsFilesetNamePutv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewFilesetsFilesetNamePutv2ParamsWithContext(ctx context.Context) *FilesetsFilesetNamePutv2Params {
	var ()
	return &FilesetsFilesetNamePutv2Params{

		Context: ctx,
	}
}

// NewFilesetsFilesetNamePutv2ParamsWithHTTPClient creates a new FilesetsFilesetNamePutv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFilesetsFilesetNamePutv2ParamsWithHTTPClient(client *http.Client) *FilesetsFilesetNamePutv2Params {
	var ()
	return &FilesetsFilesetNamePutv2Params{
		HTTPClient: client,
	}
}

/*FilesetsFilesetNamePutv2Params contains all the parameters to send to the API endpoint
for the filesets fileset name putv2 operation typically these are written to a http.Request
*/
type FilesetsFilesetNamePutv2Params struct {

	/*Body*/
	Body *models.FilesetChange
	/*FilesetName
	  The fileset name

	*/
	FilesetName string
	/*FilesystemName
	  The filesystem name, :all:, :all\_local: or :all\_remote:

	*/
	FilesystemName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) WithTimeout(timeout time.Duration) *FilesetsFilesetNamePutv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) WithContext(ctx context.Context) *FilesetsFilesetNamePutv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) WithHTTPClient(client *http.Client) *FilesetsFilesetNamePutv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) WithBody(body *models.FilesetChange) *FilesetsFilesetNamePutv2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) SetBody(body *models.FilesetChange) {
	o.Body = body
}

// WithFilesetName adds the filesetName to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) WithFilesetName(filesetName string) *FilesetsFilesetNamePutv2Params {
	o.SetFilesetName(filesetName)
	return o
}

// SetFilesetName adds the filesetName to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) SetFilesetName(filesetName string) {
	o.FilesetName = filesetName
}

// WithFilesystemName adds the filesystemName to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) WithFilesystemName(filesystemName string) *FilesetsFilesetNamePutv2Params {
	o.SetFilesystemName(filesystemName)
	return o
}

// SetFilesystemName adds the filesystemName to the filesets fileset name putv2 params
func (o *FilesetsFilesetNamePutv2Params) SetFilesystemName(filesystemName string) {
	o.FilesystemName = filesystemName
}

// WriteToRequest writes these params to a swagger request
func (o *FilesetsFilesetNamePutv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param filesetName
	if err := r.SetPathParam("filesetName", o.FilesetName); err != nil {
		return err
	}

	// path param filesystemName
	if err := r.SetPathParam("filesystemName", o.FilesystemName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
