// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFilesetsUnlinkv2Params creates a new FilesetsUnlinkv2Params object
// with the default values initialized.
func NewFilesetsUnlinkv2Params() *FilesetsUnlinkv2Params {
	var ()
	return &FilesetsUnlinkv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewFilesetsUnlinkv2ParamsWithTimeout creates a new FilesetsUnlinkv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewFilesetsUnlinkv2ParamsWithTimeout(timeout time.Duration) *FilesetsUnlinkv2Params {
	var ()
	return &FilesetsUnlinkv2Params{

		timeout: timeout,
	}
}

// NewFilesetsUnlinkv2ParamsWithContext creates a new FilesetsUnlinkv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewFilesetsUnlinkv2ParamsWithContext(ctx context.Context) *FilesetsUnlinkv2Params {
	var ()
	return &FilesetsUnlinkv2Params{

		Context: ctx,
	}
}

// NewFilesetsUnlinkv2ParamsWithHTTPClient creates a new FilesetsUnlinkv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewFilesetsUnlinkv2ParamsWithHTTPClient(client *http.Client) *FilesetsUnlinkv2Params {
	var ()
	return &FilesetsUnlinkv2Params{
		HTTPClient: client,
	}
}

/*FilesetsUnlinkv2Params contains all the parameters to send to the API endpoint
for the filesets unlinkv2 operation typically these are written to a http.Request
*/
type FilesetsUnlinkv2Params struct {

	/*FilesetName
	  The fileset name

	*/
	FilesetName string
	/*FilesystemName
	  The filesystem name, :all:, :all\_local: or :all\_remote:

	*/
	FilesystemName string
	/*Force
	  Specifies if the unlink should be forced. Default is false.

	*/
	Force *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) WithTimeout(timeout time.Duration) *FilesetsUnlinkv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) WithContext(ctx context.Context) *FilesetsUnlinkv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) WithHTTPClient(client *http.Client) *FilesetsUnlinkv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFilesetName adds the filesetName to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) WithFilesetName(filesetName string) *FilesetsUnlinkv2Params {
	o.SetFilesetName(filesetName)
	return o
}

// SetFilesetName adds the filesetName to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) SetFilesetName(filesetName string) {
	o.FilesetName = filesetName
}

// WithFilesystemName adds the filesystemName to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) WithFilesystemName(filesystemName string) *FilesetsUnlinkv2Params {
	o.SetFilesystemName(filesystemName)
	return o
}

// SetFilesystemName adds the filesystemName to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) SetFilesystemName(filesystemName string) {
	o.FilesystemName = filesystemName
}

// WithForce adds the force to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) WithForce(force *bool) *FilesetsUnlinkv2Params {
	o.SetForce(force)
	return o
}

// SetForce adds the force to the filesets unlinkv2 params
func (o *FilesetsUnlinkv2Params) SetForce(force *bool) {
	o.Force = force
}

// WriteToRequest writes these params to a swagger request
func (o *FilesetsUnlinkv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param filesetName
	if err := r.SetPathParam("filesetName", o.FilesetName); err != nil {
		return err
	}

	// path param filesystemName
	if err := r.SetPathParam("filesystemName", o.FilesystemName); err != nil {
		return err
	}

	if o.Force != nil {

		// query param force
		var qrForce bool
		if o.Force != nil {
			qrForce = *o.Force
		}
		qForce := swag.FormatBool(qrForce)
		if qForce != "" {
			if err := r.SetQueryParam("force", qForce); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
