// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// JobsGetv2Reader is a Reader for the JobsGetv2 structure.
type JobsGetv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JobsGetv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewJobsGetv2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewJobsGetv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewJobsGetv2OK creates a JobsGetv2OK with default headers values
func NewJobsGetv2OK() *JobsGetv2OK {
	return &JobsGetv2OK{}
}

/*JobsGetv2OK handles this case with default header values.

successful operation
*/
type JobsGetv2OK struct {
	Payload *models.JobInlineResponse200
}

func (o *JobsGetv2OK) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/jobs][%d] jobsGetv2OK  %+v", 200, o.Payload)
}

func (o *JobsGetv2OK) GetPayload() *models.JobInlineResponse200 {
	return o.Payload
}

func (o *JobsGetv2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JobInlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJobsGetv2InternalServerError creates a JobsGetv2InternalServerError with default headers values
func NewJobsGetv2InternalServerError() *JobsGetv2InternalServerError {
	return &JobsGetv2InternalServerError{}
}

/*JobsGetv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type JobsGetv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *JobsGetv2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/jobs][%d] jobsGetv2InternalServerError  %+v", 500, o.Payload)
}

func (o *JobsGetv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *JobsGetv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
