// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NewNfsExportPostParams creates a new NfsExportPostParams object
// with the default values initialized.
func NewNfsExportPostParams() *NfsExportPostParams {
	var ()
	return &NfsExportPostParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewNfsExportPostParamsWithTimeout creates a new NfsExportPostParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewNfsExportPostParamsWithTimeout(timeout time.Duration) *NfsExportPostParams {
	var ()
	return &NfsExportPostParams{

		timeout: timeout,
	}
}

// NewNfsExportPostParamsWithContext creates a new NfsExportPostParams object
// with the default values initialized, and the ability to set a context for a request
func NewNfsExportPostParamsWithContext(ctx context.Context) *NfsExportPostParams {
	var ()
	return &NfsExportPostParams{

		Context: ctx,
	}
}

// NewNfsExportPostParamsWithHTTPClient creates a new NfsExportPostParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNfsExportPostParamsWithHTTPClient(client *http.Client) *NfsExportPostParams {
	var ()
	return &NfsExportPostParams{
		HTTPClient: client,
	}
}

/*NfsExportPostParams contains all the parameters to send to the API endpoint
for the nfs export post operation typically these are written to a http.Request
*/
type NfsExportPostParams struct {

	/*Body*/
	Body *models.NfsExportCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the nfs export post params
func (o *NfsExportPostParams) WithTimeout(timeout time.Duration) *NfsExportPostParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the nfs export post params
func (o *NfsExportPostParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the nfs export post params
func (o *NfsExportPostParams) WithContext(ctx context.Context) *NfsExportPostParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the nfs export post params
func (o *NfsExportPostParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the nfs export post params
func (o *NfsExportPostParams) WithHTTPClient(client *http.Client) *NfsExportPostParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the nfs export post params
func (o *NfsExportPostParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the nfs export post params
func (o *NfsExportPostParams) WithBody(body *models.NfsExportCreate) *NfsExportPostParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the nfs export post params
func (o *NfsExportPostParams) SetBody(body *models.NfsExportCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *NfsExportPostParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
