// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NfsExportPathPutReader is a Reader for the NfsExportPathPut structure.
type NfsExportPathPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NfsExportPathPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewNfsExportPathPutAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNfsExportPathPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewNfsExportPathPutInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNfsExportPathPutAccepted creates a NfsExportPathPutAccepted with default headers values
func NewNfsExportPathPutAccepted() *NfsExportPathPutAccepted {
	return &NfsExportPathPutAccepted{}
}

/*NfsExportPathPutAccepted handles this case with default header values.

successful operation
*/
type NfsExportPathPutAccepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *NfsExportPathPutAccepted) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/nfs/exports/{exportPath}][%d] nfsExportPathPutAccepted  %+v", 202, o.Payload)
}

func (o *NfsExportPathPutAccepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *NfsExportPathPutAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNfsExportPathPutBadRequest creates a NfsExportPathPutBadRequest with default headers values
func NewNfsExportPathPutBadRequest() *NfsExportPathPutBadRequest {
	return &NfsExportPathPutBadRequest{}
}

/*NfsExportPathPutBadRequest handles this case with default header values.

NFS export not found
*/
type NfsExportPathPutBadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *NfsExportPathPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/nfs/exports/{exportPath}][%d] nfsExportPathPutBadRequest  %+v", 400, o.Payload)
}

func (o *NfsExportPathPutBadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *NfsExportPathPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNfsExportPathPutInternalServerError creates a NfsExportPathPutInternalServerError with default headers values
func NewNfsExportPathPutInternalServerError() *NfsExportPathPutInternalServerError {
	return &NfsExportPathPutInternalServerError{}
}

/*NfsExportPathPutInternalServerError handles this case with default header values.

Internal Server Error
*/
type NfsExportPathPutInternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *NfsExportPathPutInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/nfs/exports/{exportPath}][%d] nfsExportPathPutInternalServerError  %+v", 500, o.Payload)
}

func (o *NfsExportPathPutInternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *NfsExportPathPutInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
