// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NewNodesPostv2Params creates a new NodesPostv2Params object
// with the default values initialized.
func NewNodesPostv2Params() *NodesPostv2Params {
	var ()
	return &NodesPostv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNodesPostv2ParamsWithTimeout creates a new NodesPostv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNodesPostv2ParamsWithTimeout(timeout time.Duration) *NodesPostv2Params {
	var ()
	return &NodesPostv2Params{

		timeout: timeout,
	}
}

// NewNodesPostv2ParamsWithContext creates a new NodesPostv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewNodesPostv2ParamsWithContext(ctx context.Context) *NodesPostv2Params {
	var ()
	return &NodesPostv2Params{

		Context: ctx,
	}
}

// NewNodesPostv2ParamsWithHTTPClient creates a new NodesPostv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNodesPostv2ParamsWithHTTPClient(client *http.Client) *NodesPostv2Params {
	var ()
	return &NodesPostv2Params{
		HTTPClient: client,
	}
}

/*NodesPostv2Params contains all the parameters to send to the API endpoint
for the nodes postv2 operation typically these are written to a http.Request
*/
type NodesPostv2Params struct {

	/*Body*/
	Body *models.NodeCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the nodes postv2 params
func (o *NodesPostv2Params) WithTimeout(timeout time.Duration) *NodesPostv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the nodes postv2 params
func (o *NodesPostv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the nodes postv2 params
func (o *NodesPostv2Params) WithContext(ctx context.Context) *NodesPostv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the nodes postv2 params
func (o *NodesPostv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the nodes postv2 params
func (o *NodesPostv2Params) WithHTTPClient(client *http.Client) *NodesPostv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the nodes postv2 params
func (o *NodesPostv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the nodes postv2 params
func (o *NodesPostv2Params) WithBody(body *models.NodeCreate) *NodesPostv2Params {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the nodes postv2 params
func (o *NodesPostv2Params) SetBody(body *models.NodeCreate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *NodesPostv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
