// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// NodeclassNameDeletev2Reader is a Reader for the NodeclassNameDeletev2 structure.
type NodeclassNameDeletev2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *NodeclassNameDeletev2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewNodeclassNameDeletev2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewNodeclassNameDeletev2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewNodeclassNameDeletev2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewNodeclassNameDeletev2Accepted creates a NodeclassNameDeletev2Accepted with default headers values
func NewNodeclassNameDeletev2Accepted() *NodeclassNameDeletev2Accepted {
	return &NodeclassNameDeletev2Accepted{}
}

/*NodeclassNameDeletev2Accepted handles this case with default header values.

successful operation
*/
type NodeclassNameDeletev2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *NodeclassNameDeletev2Accepted) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/nodeclasses/{nodeclassName}][%d] nodeclassNameDeletev2Accepted  %+v", 202, o.Payload)
}

func (o *NodeclassNameDeletev2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *NodeclassNameDeletev2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNodeclassNameDeletev2BadRequest creates a NodeclassNameDeletev2BadRequest with default headers values
func NewNodeclassNameDeletev2BadRequest() *NodeclassNameDeletev2BadRequest {
	return &NodeclassNameDeletev2BadRequest{}
}

/*NodeclassNameDeletev2BadRequest handles this case with default header values.

Invalid request
*/
type NodeclassNameDeletev2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *NodeclassNameDeletev2BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/nodeclasses/{nodeclassName}][%d] nodeclassNameDeletev2BadRequest  %+v", 400, o.Payload)
}

func (o *NodeclassNameDeletev2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *NodeclassNameDeletev2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewNodeclassNameDeletev2InternalServerError creates a NodeclassNameDeletev2InternalServerError with default headers values
func NewNodeclassNameDeletev2InternalServerError() *NodeclassNameDeletev2InternalServerError {
	return &NodeclassNameDeletev2InternalServerError{}
}

/*NodeclassNameDeletev2InternalServerError handles this case with default header values.

Internal Server Error
*/
type NodeclassNameDeletev2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *NodeclassNameDeletev2InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/nodeclasses/{nodeclassName}][%d] nodeclassNameDeletev2InternalServerError  %+v", 500, o.Payload)
}

func (o *NodeclassNameDeletev2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *NodeclassNameDeletev2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
