// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewNodesListMappingv20Params creates a new NodesListMappingv20Params object
// with the default values initialized.
func NewNodesListMappingv20Params() *NodesListMappingv20Params {
	var ()
	return &NodesListMappingv20Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewNodesListMappingv20ParamsWithTimeout creates a new NodesListMappingv20Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewNodesListMappingv20ParamsWithTimeout(timeout time.Duration) *NodesListMappingv20Params {
	var ()
	return &NodesListMappingv20Params{

		timeout: timeout,
	}
}

// NewNodesListMappingv20ParamsWithContext creates a new NodesListMappingv20Params object
// with the default values initialized, and the ability to set a context for a request
func NewNodesListMappingv20ParamsWithContext(ctx context.Context) *NodesListMappingv20Params {
	var ()
	return &NodesListMappingv20Params{

		Context: ctx,
	}
}

// NewNodesListMappingv20ParamsWithHTTPClient creates a new NodesListMappingv20Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewNodesListMappingv20ParamsWithHTTPClient(client *http.Client) *NodesListMappingv20Params {
	var ()
	return &NodesListMappingv20Params{
		HTTPClient: client,
	}
}

/*NodesListMappingv20Params contains all the parameters to send to the API endpoint
for the nodes list mappingv2 0 operation typically these are written to a http.Request
*/
type NodesListMappingv20Params struct {

	/*Fields
	  Comma separated list of fields to be included in response. ':all:' selects all available fields.

	*/
	Fields *string
	/*MappingName
	  node mapping name

	*/
	MappingName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) WithTimeout(timeout time.Duration) *NodesListMappingv20Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) WithContext(ctx context.Context) *NodesListMappingv20Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) WithHTTPClient(client *http.Client) *NodesListMappingv20Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) WithFields(fields *string) *NodesListMappingv20Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithMappingName adds the mappingName to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) WithMappingName(mappingName string) *NodesListMappingv20Params {
	o.SetMappingName(mappingName)
	return o
}

// SetMappingName adds the mappingName to the nodes list mappingv2 0 params
func (o *NodesListMappingv20Params) SetMappingName(mappingName string) {
	o.MappingName = mappingName
}

// WriteToRequest writes these params to a swagger request
func (o *NodesListMappingv20Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param mappingName
	if err := r.SetPathParam("mappingName", o.MappingName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
