// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOwningClustersGetv2Params creates a new OwningClustersGetv2Params object
// with the default values initialized.
func NewOwningClustersGetv2Params() *OwningClustersGetv2Params {

	return &OwningClustersGetv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewOwningClustersGetv2ParamsWithTimeout creates a new OwningClustersGetv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewOwningClustersGetv2ParamsWithTimeout(timeout time.Duration) *OwningClustersGetv2Params {

	return &OwningClustersGetv2Params{

		timeout: timeout,
	}
}

// NewOwningClustersGetv2ParamsWithContext creates a new OwningClustersGetv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewOwningClustersGetv2ParamsWithContext(ctx context.Context) *OwningClustersGetv2Params {

	return &OwningClustersGetv2Params{

		Context: ctx,
	}
}

// NewOwningClustersGetv2ParamsWithHTTPClient creates a new OwningClustersGetv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOwningClustersGetv2ParamsWithHTTPClient(client *http.Client) *OwningClustersGetv2Params {

	return &OwningClustersGetv2Params{
		HTTPClient: client,
	}
}

/*OwningClustersGetv2Params contains all the parameters to send to the API endpoint
for the owning clusters getv2 operation typically these are written to a http.Request
*/
type OwningClustersGetv2Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the owning clusters getv2 params
func (o *OwningClustersGetv2Params) WithTimeout(timeout time.Duration) *OwningClustersGetv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the owning clusters getv2 params
func (o *OwningClustersGetv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the owning clusters getv2 params
func (o *OwningClustersGetv2Params) WithContext(ctx context.Context) *OwningClustersGetv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the owning clusters getv2 params
func (o *OwningClustersGetv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the owning clusters getv2 params
func (o *OwningClustersGetv2Params) WithHTTPClient(client *http.Client) *OwningClustersGetv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the owning clusters getv2 params
func (o *OwningClustersGetv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OwningClustersGetv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
