// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// OwningClustersPostv2Reader is a Reader for the OwningClustersPostv2 structure.
type OwningClustersPostv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OwningClustersPostv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewOwningClustersPostv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOwningClustersPostv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewOwningClustersPostv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOwningClustersPostv2Accepted creates a OwningClustersPostv2Accepted with default headers values
func NewOwningClustersPostv2Accepted() *OwningClustersPostv2Accepted {
	return &OwningClustersPostv2Accepted{}
}

/*OwningClustersPostv2Accepted handles this case with default header values.

successful operation
*/
type OwningClustersPostv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *OwningClustersPostv2Accepted) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/remotemount/owningclusters][%d] owningClustersPostv2Accepted  %+v", 202, o.Payload)
}

func (o *OwningClustersPostv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *OwningClustersPostv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOwningClustersPostv2BadRequest creates a OwningClustersPostv2BadRequest with default headers values
func NewOwningClustersPostv2BadRequest() *OwningClustersPostv2BadRequest {
	return &OwningClustersPostv2BadRequest{}
}

/*OwningClustersPostv2BadRequest handles this case with default header values.

Invalid request
*/
type OwningClustersPostv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *OwningClustersPostv2BadRequest) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/remotemount/owningclusters][%d] owningClustersPostv2BadRequest  %+v", 400, o.Payload)
}

func (o *OwningClustersPostv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *OwningClustersPostv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOwningClustersPostv2InternalServerError creates a OwningClustersPostv2InternalServerError with default headers values
func NewOwningClustersPostv2InternalServerError() *OwningClustersPostv2InternalServerError {
	return &OwningClustersPostv2InternalServerError{}
}

/*OwningClustersPostv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type OwningClustersPostv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *OwningClustersPostv2InternalServerError) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/remotemount/owningclusters][%d] owningClustersPostv2InternalServerError  %+v", 500, o.Payload)
}

func (o *OwningClustersPostv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *OwningClustersPostv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
