// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// OwningClustersPutv2Reader is a Reader for the OwningClustersPutv2 structure.
type OwningClustersPutv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OwningClustersPutv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewOwningClustersPutv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewOwningClustersPutv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewOwningClustersPutv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewOwningClustersPutv2Accepted creates a OwningClustersPutv2Accepted with default headers values
func NewOwningClustersPutv2Accepted() *OwningClustersPutv2Accepted {
	return &OwningClustersPutv2Accepted{}
}

/*OwningClustersPutv2Accepted handles this case with default header values.

successful operation
*/
type OwningClustersPutv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *OwningClustersPutv2Accepted) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/remotemount/owningclusters/{owningCluster}][%d] owningClustersPutv2Accepted  %+v", 202, o.Payload)
}

func (o *OwningClustersPutv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *OwningClustersPutv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOwningClustersPutv2BadRequest creates a OwningClustersPutv2BadRequest with default headers values
func NewOwningClustersPutv2BadRequest() *OwningClustersPutv2BadRequest {
	return &OwningClustersPutv2BadRequest{}
}

/*OwningClustersPutv2BadRequest handles this case with default header values.

Invalid request
*/
type OwningClustersPutv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *OwningClustersPutv2BadRequest) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/remotemount/owningclusters/{owningCluster}][%d] owningClustersPutv2BadRequest  %+v", 400, o.Payload)
}

func (o *OwningClustersPutv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *OwningClustersPutv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewOwningClustersPutv2InternalServerError creates a OwningClustersPutv2InternalServerError with default headers values
func NewOwningClustersPutv2InternalServerError() *OwningClustersPutv2InternalServerError {
	return &OwningClustersPutv2InternalServerError{}
}

/*OwningClustersPutv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type OwningClustersPutv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *OwningClustersPutv2InternalServerError) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/remotemount/owningclusters/{owningCluster}][%d] owningClustersPutv2InternalServerError  %+v", 500, o.Payload)
}

func (o *OwningClustersPutv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *OwningClustersPutv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
