// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// PerformanceDataStatsv2Reader is a Reader for the PerformanceDataStatsv2 structure.
type PerformanceDataStatsv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PerformanceDataStatsv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPerformanceDataStatsv2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPerformanceDataStatsv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPerformanceDataStatsv2OK creates a PerformanceDataStatsv2OK with default headers values
func NewPerformanceDataStatsv2OK() *PerformanceDataStatsv2OK {
	return &PerformanceDataStatsv2OK{}
}

/*PerformanceDataStatsv2OK handles this case with default header values.

Performance Data
*/
type PerformanceDataStatsv2OK struct {
	Payload *models.PerformanceDataInlineResponse200
}

func (o *PerformanceDataStatsv2OK) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/perfmon/stats][%d] performanceDataStatsv2OK  %+v", 200, o.Payload)
}

func (o *PerformanceDataStatsv2OK) GetPayload() *models.PerformanceDataInlineResponse200 {
	return o.Payload
}

func (o *PerformanceDataStatsv2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PerformanceDataInlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPerformanceDataStatsv2InternalServerError creates a PerformanceDataStatsv2InternalServerError with default headers values
func NewPerformanceDataStatsv2InternalServerError() *PerformanceDataStatsv2InternalServerError {
	return &PerformanceDataStatsv2InternalServerError{}
}

/*PerformanceDataStatsv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type PerformanceDataStatsv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *PerformanceDataStatsv2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/perfmon/stats][%d] performanceDataStatsv2InternalServerError  %+v", 500, o.Payload)
}

func (o *PerformanceDataStatsv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *PerformanceDataStatsv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
