// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// PsnapsFilesetsSnapshotNameDeletev2Reader is a Reader for the PsnapsFilesetsSnapshotNameDeletev2 structure.
type PsnapsFilesetsSnapshotNameDeletev2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PsnapsFilesetsSnapshotNameDeletev2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewPsnapsFilesetsSnapshotNameDeletev2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPsnapsFilesetsSnapshotNameDeletev2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPsnapsFilesetsSnapshotNameDeletev2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPsnapsFilesetsSnapshotNameDeletev2Accepted creates a PsnapsFilesetsSnapshotNameDeletev2Accepted with default headers values
func NewPsnapsFilesetsSnapshotNameDeletev2Accepted() *PsnapsFilesetsSnapshotNameDeletev2Accepted {
	return &PsnapsFilesetsSnapshotNameDeletev2Accepted{}
}

/*PsnapsFilesetsSnapshotNameDeletev2Accepted handles this case with default header values.

successful operation
*/
type PsnapsFilesetsSnapshotNameDeletev2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *PsnapsFilesetsSnapshotNameDeletev2Accepted) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/psnaps/{snapshotName}][%d] psnapsFilesetsSnapshotNameDeletev2Accepted  %+v", 202, o.Payload)
}

func (o *PsnapsFilesetsSnapshotNameDeletev2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *PsnapsFilesetsSnapshotNameDeletev2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPsnapsFilesetsSnapshotNameDeletev2BadRequest creates a PsnapsFilesetsSnapshotNameDeletev2BadRequest with default headers values
func NewPsnapsFilesetsSnapshotNameDeletev2BadRequest() *PsnapsFilesetsSnapshotNameDeletev2BadRequest {
	return &PsnapsFilesetsSnapshotNameDeletev2BadRequest{}
}

/*PsnapsFilesetsSnapshotNameDeletev2BadRequest handles this case with default header values.

Invalid request
*/
type PsnapsFilesetsSnapshotNameDeletev2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *PsnapsFilesetsSnapshotNameDeletev2BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/psnaps/{snapshotName}][%d] psnapsFilesetsSnapshotNameDeletev2BadRequest  %+v", 400, o.Payload)
}

func (o *PsnapsFilesetsSnapshotNameDeletev2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *PsnapsFilesetsSnapshotNameDeletev2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPsnapsFilesetsSnapshotNameDeletev2InternalServerError creates a PsnapsFilesetsSnapshotNameDeletev2InternalServerError with default headers values
func NewPsnapsFilesetsSnapshotNameDeletev2InternalServerError() *PsnapsFilesetsSnapshotNameDeletev2InternalServerError {
	return &PsnapsFilesetsSnapshotNameDeletev2InternalServerError{}
}

/*PsnapsFilesetsSnapshotNameDeletev2InternalServerError handles this case with default header values.

Internal Server Error
*/
type PsnapsFilesetsSnapshotNameDeletev2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *PsnapsFilesetsSnapshotNameDeletev2InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/psnaps/{snapshotName}][%d] psnapsFilesetsSnapshotNameDeletev2InternalServerError  %+v", 500, o.Payload)
}

func (o *PsnapsFilesetsSnapshotNameDeletev2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *PsnapsFilesetsSnapshotNameDeletev2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
