// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// QuotasPostv20Reader is a Reader for the QuotasPostv20 structure.
type QuotasPostv20Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QuotasPostv20Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewQuotasPostv20Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewQuotasPostv20InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewQuotasPostv20Accepted creates a QuotasPostv20Accepted with default headers values
func NewQuotasPostv20Accepted() *QuotasPostv20Accepted {
	return &QuotasPostv20Accepted{}
}

/*QuotasPostv20Accepted handles this case with default header values.

successful operation
*/
type QuotasPostv20Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *QuotasPostv20Accepted) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/quotas][%d] quotasPostv20Accepted  %+v", 202, o.Payload)
}

func (o *QuotasPostv20Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *QuotasPostv20Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQuotasPostv20InternalServerError creates a QuotasPostv20InternalServerError with default headers values
func NewQuotasPostv20InternalServerError() *QuotasPostv20InternalServerError {
	return &QuotasPostv20InternalServerError{}
}

/*QuotasPostv20InternalServerError handles this case with default header values.

Internal Server Error
*/
type QuotasPostv20InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *QuotasPostv20InternalServerError) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/quotas][%d] quotasPostv20InternalServerError  %+v", 500, o.Payload)
}

func (o *QuotasPostv20InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *QuotasPostv20InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
