// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQuotaDefaultsFilesetGetv2Params creates a new QuotaDefaultsFilesetGetv2Params object
// with the default values initialized.
func NewQuotaDefaultsFilesetGetv2Params() *QuotaDefaultsFilesetGetv2Params {
	var ()
	return &QuotaDefaultsFilesetGetv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewQuotaDefaultsFilesetGetv2ParamsWithTimeout creates a new QuotaDefaultsFilesetGetv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewQuotaDefaultsFilesetGetv2ParamsWithTimeout(timeout time.Duration) *QuotaDefaultsFilesetGetv2Params {
	var ()
	return &QuotaDefaultsFilesetGetv2Params{

		timeout: timeout,
	}
}

// NewQuotaDefaultsFilesetGetv2ParamsWithContext creates a new QuotaDefaultsFilesetGetv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewQuotaDefaultsFilesetGetv2ParamsWithContext(ctx context.Context) *QuotaDefaultsFilesetGetv2Params {
	var ()
	return &QuotaDefaultsFilesetGetv2Params{

		Context: ctx,
	}
}

// NewQuotaDefaultsFilesetGetv2ParamsWithHTTPClient creates a new QuotaDefaultsFilesetGetv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewQuotaDefaultsFilesetGetv2ParamsWithHTTPClient(client *http.Client) *QuotaDefaultsFilesetGetv2Params {
	var ()
	return &QuotaDefaultsFilesetGetv2Params{
		HTTPClient: client,
	}
}

/*QuotaDefaultsFilesetGetv2Params contains all the parameters to send to the API endpoint
for the quota defaults fileset getv2 operation typically these are written to a http.Request
*/
type QuotaDefaultsFilesetGetv2Params struct {

	/*Fields
	  Comma separated list of fields to be included in response. ':all:' selects all available fields.

	*/
	Fields *string
	/*FilesetName
	  The fileset name or :all:

	*/
	FilesetName string
	/*FilesystemName
	  The filesystem name or :all:

	*/
	FilesystemName string
	/*Filter
	  Filter objects by expression, e.g. 'quotaType=GRP,deviceName=gpfs0'

	*/
	Filter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) WithTimeout(timeout time.Duration) *QuotaDefaultsFilesetGetv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) WithContext(ctx context.Context) *QuotaDefaultsFilesetGetv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) WithHTTPClient(client *http.Client) *QuotaDefaultsFilesetGetv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) WithFields(fields *string) *QuotaDefaultsFilesetGetv2Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithFilesetName adds the filesetName to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) WithFilesetName(filesetName string) *QuotaDefaultsFilesetGetv2Params {
	o.SetFilesetName(filesetName)
	return o
}

// SetFilesetName adds the filesetName to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) SetFilesetName(filesetName string) {
	o.FilesetName = filesetName
}

// WithFilesystemName adds the filesystemName to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) WithFilesystemName(filesystemName string) *QuotaDefaultsFilesetGetv2Params {
	o.SetFilesystemName(filesystemName)
	return o
}

// SetFilesystemName adds the filesystemName to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) SetFilesystemName(filesystemName string) {
	o.FilesystemName = filesystemName
}

// WithFilter adds the filter to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) WithFilter(filter *string) *QuotaDefaultsFilesetGetv2Params {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the quota defaults fileset getv2 params
func (o *QuotaDefaultsFilesetGetv2Params) SetFilter(filter *string) {
	o.Filter = filter
}

// WriteToRequest writes these params to a swagger request
func (o *QuotaDefaultsFilesetGetv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param filesetName
	if err := r.SetPathParam("filesetName", o.FilesetName); err != nil {
		return err
	}

	// path param filesystemName
	if err := r.SetPathParam("filesystemName", o.FilesystemName); err != nil {
		return err
	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
