// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRecoveryGroupGetv20Params creates a new RecoveryGroupGetv20Params object
// with the default values initialized.
func NewRecoveryGroupGetv20Params() *RecoveryGroupGetv20Params {
	var ()
	return &RecoveryGroupGetv20Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewRecoveryGroupGetv20ParamsWithTimeout creates a new RecoveryGroupGetv20Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewRecoveryGroupGetv20ParamsWithTimeout(timeout time.Duration) *RecoveryGroupGetv20Params {
	var ()
	return &RecoveryGroupGetv20Params{

		timeout: timeout,
	}
}

// NewRecoveryGroupGetv20ParamsWithContext creates a new RecoveryGroupGetv20Params object
// with the default values initialized, and the ability to set a context for a request
func NewRecoveryGroupGetv20ParamsWithContext(ctx context.Context) *RecoveryGroupGetv20Params {
	var ()
	return &RecoveryGroupGetv20Params{

		Context: ctx,
	}
}

// NewRecoveryGroupGetv20ParamsWithHTTPClient creates a new RecoveryGroupGetv20Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRecoveryGroupGetv20ParamsWithHTTPClient(client *http.Client) *RecoveryGroupGetv20Params {
	var ()
	return &RecoveryGroupGetv20Params{
		HTTPClient: client,
	}
}

/*RecoveryGroupGetv20Params contains all the parameters to send to the API endpoint
for the recovery group getv2 0 operation typically these are written to a http.Request
*/
type RecoveryGroupGetv20Params struct {

	/*Fields
	  Comma separated list of fields to be included in response. ':all:' selects all available fields.

	*/
	Fields *string
	/*Filter
	  Filter objects by expression, e.g. 'status=HEALTHY,entityType=FILESET'

	*/
	Filter *string
	/*RecoveryGroupName
	  The recovery group name, :all:

	*/
	RecoveryGroupName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) WithTimeout(timeout time.Duration) *RecoveryGroupGetv20Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) WithContext(ctx context.Context) *RecoveryGroupGetv20Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) WithHTTPClient(client *http.Client) *RecoveryGroupGetv20Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) WithFields(fields *string) *RecoveryGroupGetv20Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithFilter adds the filter to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) WithFilter(filter *string) *RecoveryGroupGetv20Params {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) SetFilter(filter *string) {
	o.Filter = filter
}

// WithRecoveryGroupName adds the recoveryGroupName to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) WithRecoveryGroupName(recoveryGroupName string) *RecoveryGroupGetv20Params {
	o.SetRecoveryGroupName(recoveryGroupName)
	return o
}

// SetRecoveryGroupName adds the recoveryGroupName to the recovery group getv2 0 params
func (o *RecoveryGroupGetv20Params) SetRecoveryGroupName(recoveryGroupName string) {
	o.RecoveryGroupName = recoveryGroupName
}

// WriteToRequest writes these params to a swagger request
func (o *RecoveryGroupGetv20Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	// path param recoveryGroupName
	if err := r.SetPathParam("recoveryGroupName", o.RecoveryGroupName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
