// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// RecoveryGroupGetv20Reader is a Reader for the RecoveryGroupGetv20 structure.
type RecoveryGroupGetv20Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RecoveryGroupGetv20Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRecoveryGroupGetv20OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewRecoveryGroupGetv20InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRecoveryGroupGetv20OK creates a RecoveryGroupGetv20OK with default headers values
func NewRecoveryGroupGetv20OK() *RecoveryGroupGetv20OK {
	return &RecoveryGroupGetv20OK{}
}

/*RecoveryGroupGetv20OK handles this case with default header values.

successful operation
*/
type RecoveryGroupGetv20OK struct {
	Payload *models.VDiskInlineResponse200
}

func (o *RecoveryGroupGetv20OK) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/gnr/recoverygroups/{recoveryGroupName}/vdisks][%d] recoveryGroupGetv20OK  %+v", 200, o.Payload)
}

func (o *RecoveryGroupGetv20OK) GetPayload() *models.VDiskInlineResponse200 {
	return o.Payload
}

func (o *RecoveryGroupGetv20OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VDiskInlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRecoveryGroupGetv20InternalServerError creates a RecoveryGroupGetv20InternalServerError with default headers values
func NewRecoveryGroupGetv20InternalServerError() *RecoveryGroupGetv20InternalServerError {
	return &RecoveryGroupGetv20InternalServerError{}
}

/*RecoveryGroupGetv20InternalServerError handles this case with default header values.

Internal Server Error
*/
type RecoveryGroupGetv20InternalServerError struct {
	Payload *models.VDiskInlineResponse200
}

func (o *RecoveryGroupGetv20InternalServerError) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/gnr/recoverygroups/{recoveryGroupName}/vdisks][%d] recoveryGroupGetv20InternalServerError  %+v", 500, o.Payload)
}

func (o *RecoveryGroupGetv20InternalServerError) GetPayload() *models.VDiskInlineResponse200 {
	return o.Payload
}

func (o *RecoveryGroupGetv20InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VDiskInlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
