// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// RemoteClustersDenyAccessv2Reader is a Reader for the RemoteClustersDenyAccessv2 structure.
type RemoteClustersDenyAccessv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoteClustersDenyAccessv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewRemoteClustersDenyAccessv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoteClustersDenyAccessv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoteClustersDenyAccessv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoteClustersDenyAccessv2Accepted creates a RemoteClustersDenyAccessv2Accepted with default headers values
func NewRemoteClustersDenyAccessv2Accepted() *RemoteClustersDenyAccessv2Accepted {
	return &RemoteClustersDenyAccessv2Accepted{}
}

/*RemoteClustersDenyAccessv2Accepted handles this case with default header values.

successful operation
*/
type RemoteClustersDenyAccessv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *RemoteClustersDenyAccessv2Accepted) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/remotemount/remoteclusters/{remoteCluster}/deny/{owningClusterFilesystem}][%d] remoteClustersDenyAccessv2Accepted  %+v", 202, o.Payload)
}

func (o *RemoteClustersDenyAccessv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *RemoteClustersDenyAccessv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoteClustersDenyAccessv2BadRequest creates a RemoteClustersDenyAccessv2BadRequest with default headers values
func NewRemoteClustersDenyAccessv2BadRequest() *RemoteClustersDenyAccessv2BadRequest {
	return &RemoteClustersDenyAccessv2BadRequest{}
}

/*RemoteClustersDenyAccessv2BadRequest handles this case with default header values.

Invalid request
*/
type RemoteClustersDenyAccessv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *RemoteClustersDenyAccessv2BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/remotemount/remoteclusters/{remoteCluster}/deny/{owningClusterFilesystem}][%d] remoteClustersDenyAccessv2BadRequest  %+v", 400, o.Payload)
}

func (o *RemoteClustersDenyAccessv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *RemoteClustersDenyAccessv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoteClustersDenyAccessv2InternalServerError creates a RemoteClustersDenyAccessv2InternalServerError with default headers values
func NewRemoteClustersDenyAccessv2InternalServerError() *RemoteClustersDenyAccessv2InternalServerError {
	return &RemoteClustersDenyAccessv2InternalServerError{}
}

/*RemoteClustersDenyAccessv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type RemoteClustersDenyAccessv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *RemoteClustersDenyAccessv2InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/remotemount/remoteclusters/{remoteCluster}/deny/{owningClusterFilesystem}][%d] remoteClustersDenyAccessv2InternalServerError  %+v", 500, o.Payload)
}

func (o *RemoteClustersDenyAccessv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *RemoteClustersDenyAccessv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
