// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoteClustersGetv2Params creates a new RemoteClustersGetv2Params object
// with the default values initialized.
func NewRemoteClustersGetv2Params() *RemoteClustersGetv2Params {

	return &RemoteClustersGetv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoteClustersGetv2ParamsWithTimeout creates a new RemoteClustersGetv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoteClustersGetv2ParamsWithTimeout(timeout time.Duration) *RemoteClustersGetv2Params {

	return &RemoteClustersGetv2Params{

		timeout: timeout,
	}
}

// NewRemoteClustersGetv2ParamsWithContext creates a new RemoteClustersGetv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewRemoteClustersGetv2ParamsWithContext(ctx context.Context) *RemoteClustersGetv2Params {

	return &RemoteClustersGetv2Params{

		Context: ctx,
	}
}

// NewRemoteClustersGetv2ParamsWithHTTPClient creates a new RemoteClustersGetv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoteClustersGetv2ParamsWithHTTPClient(client *http.Client) *RemoteClustersGetv2Params {

	return &RemoteClustersGetv2Params{
		HTTPClient: client,
	}
}

/*RemoteClustersGetv2Params contains all the parameters to send to the API endpoint
for the remote clusters getv2 operation typically these are written to a http.Request
*/
type RemoteClustersGetv2Params struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remote clusters getv2 params
func (o *RemoteClustersGetv2Params) WithTimeout(timeout time.Duration) *RemoteClustersGetv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remote clusters getv2 params
func (o *RemoteClustersGetv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remote clusters getv2 params
func (o *RemoteClustersGetv2Params) WithContext(ctx context.Context) *RemoteClustersGetv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remote clusters getv2 params
func (o *RemoteClustersGetv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remote clusters getv2 params
func (o *RemoteClustersGetv2Params) WithHTTPClient(client *http.Client) *RemoteClustersGetv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remote clusters getv2 params
func (o *RemoteClustersGetv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *RemoteClustersGetv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
