// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewRemoteClustersDenyAccessv2Params creates a new RemoteClustersDenyAccessv2Params object
// with the default values initialized.
func NewRemoteClustersDenyAccessv2Params() *RemoteClustersDenyAccessv2Params {
	var ()
	return &RemoteClustersDenyAccessv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoteClustersDenyAccessv2ParamsWithTimeout creates a new RemoteClustersDenyAccessv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoteClustersDenyAccessv2ParamsWithTimeout(timeout time.Duration) *RemoteClustersDenyAccessv2Params {
	var ()
	return &RemoteClustersDenyAccessv2Params{

		timeout: timeout,
	}
}

// NewRemoteClustersDenyAccessv2ParamsWithContext creates a new RemoteClustersDenyAccessv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewRemoteClustersDenyAccessv2ParamsWithContext(ctx context.Context) *RemoteClustersDenyAccessv2Params {
	var ()
	return &RemoteClustersDenyAccessv2Params{

		Context: ctx,
	}
}

// NewRemoteClustersDenyAccessv2ParamsWithHTTPClient creates a new RemoteClustersDenyAccessv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoteClustersDenyAccessv2ParamsWithHTTPClient(client *http.Client) *RemoteClustersDenyAccessv2Params {
	var ()
	return &RemoteClustersDenyAccessv2Params{
		HTTPClient: client,
	}
}

/*RemoteClustersDenyAccessv2Params contains all the parameters to send to the API endpoint
for the remote clusters deny accessv2 operation typically these are written to a http.Request
*/
type RemoteClustersDenyAccessv2Params struct {

	/*OwningClusterFilesystem
	  filesystem name or 'all'

	*/
	OwningClusterFilesystem string
	/*RemoteCluster
	  remote cluster name

	*/
	RemoteCluster string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) WithTimeout(timeout time.Duration) *RemoteClustersDenyAccessv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) WithContext(ctx context.Context) *RemoteClustersDenyAccessv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) WithHTTPClient(client *http.Client) *RemoteClustersDenyAccessv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwningClusterFilesystem adds the owningClusterFilesystem to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) WithOwningClusterFilesystem(owningClusterFilesystem string) *RemoteClustersDenyAccessv2Params {
	o.SetOwningClusterFilesystem(owningClusterFilesystem)
	return o
}

// SetOwningClusterFilesystem adds the owningClusterFilesystem to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) SetOwningClusterFilesystem(owningClusterFilesystem string) {
	o.OwningClusterFilesystem = owningClusterFilesystem
}

// WithRemoteCluster adds the remoteCluster to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) WithRemoteCluster(remoteCluster string) *RemoteClustersDenyAccessv2Params {
	o.SetRemoteCluster(remoteCluster)
	return o
}

// SetRemoteCluster adds the remoteCluster to the remote clusters deny accessv2 params
func (o *RemoteClustersDenyAccessv2Params) SetRemoteCluster(remoteCluster string) {
	o.RemoteCluster = remoteCluster
}

// WriteToRequest writes these params to a swagger request
func (o *RemoteClustersDenyAccessv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owningClusterFilesystem
	if err := r.SetPathParam("owningClusterFilesystem", o.OwningClusterFilesystem); err != nil {
		return err
	}

	// path param remoteCluster
	if err := r.SetPathParam("remoteCluster", o.RemoteCluster); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
