// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// RemoteFilesystemsGetv2Reader is a Reader for the RemoteFilesystemsGetv2 structure.
type RemoteFilesystemsGetv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoteFilesystemsGetv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRemoteFilesystemsGetv2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewRemoteFilesystemsGetv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoteFilesystemsGetv2OK creates a RemoteFilesystemsGetv2OK with default headers values
func NewRemoteFilesystemsGetv2OK() *RemoteFilesystemsGetv2OK {
	return &RemoteFilesystemsGetv2OK{}
}

/*RemoteFilesystemsGetv2OK handles this case with default header values.

successful operation
*/
type RemoteFilesystemsGetv2OK struct {
	Payload *models.RemoteFilesystemInlineResponse200
}

func (o *RemoteFilesystemsGetv2OK) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/remotemount/remotefilesystems][%d] remoteFilesystemsGetv2OK  %+v", 200, o.Payload)
}

func (o *RemoteFilesystemsGetv2OK) GetPayload() *models.RemoteFilesystemInlineResponse200 {
	return o.Payload
}

func (o *RemoteFilesystemsGetv2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RemoteFilesystemInlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoteFilesystemsGetv2InternalServerError creates a RemoteFilesystemsGetv2InternalServerError with default headers values
func NewRemoteFilesystemsGetv2InternalServerError() *RemoteFilesystemsGetv2InternalServerError {
	return &RemoteFilesystemsGetv2InternalServerError{}
}

/*RemoteFilesystemsGetv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type RemoteFilesystemsGetv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *RemoteFilesystemsGetv2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/remotemount/remotefilesystems][%d] remoteFilesystemsGetv2InternalServerError  %+v", 500, o.Payload)
}

func (o *RemoteFilesystemsGetv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *RemoteFilesystemsGetv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
