// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// RemoteFilesystemsPostv2Reader is a Reader for the RemoteFilesystemsPostv2 structure.
type RemoteFilesystemsPostv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoteFilesystemsPostv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewRemoteFilesystemsPostv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoteFilesystemsPostv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoteFilesystemsPostv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoteFilesystemsPostv2Accepted creates a RemoteFilesystemsPostv2Accepted with default headers values
func NewRemoteFilesystemsPostv2Accepted() *RemoteFilesystemsPostv2Accepted {
	return &RemoteFilesystemsPostv2Accepted{}
}

/*RemoteFilesystemsPostv2Accepted handles this case with default header values.

successful operation
*/
type RemoteFilesystemsPostv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *RemoteFilesystemsPostv2Accepted) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/remotemount/remotefilesystems][%d] remoteFilesystemsPostv2Accepted  %+v", 202, o.Payload)
}

func (o *RemoteFilesystemsPostv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *RemoteFilesystemsPostv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoteFilesystemsPostv2BadRequest creates a RemoteFilesystemsPostv2BadRequest with default headers values
func NewRemoteFilesystemsPostv2BadRequest() *RemoteFilesystemsPostv2BadRequest {
	return &RemoteFilesystemsPostv2BadRequest{}
}

/*RemoteFilesystemsPostv2BadRequest handles this case with default header values.

Invalid request
*/
type RemoteFilesystemsPostv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *RemoteFilesystemsPostv2BadRequest) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/remotemount/remotefilesystems][%d] remoteFilesystemsPostv2BadRequest  %+v", 400, o.Payload)
}

func (o *RemoteFilesystemsPostv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *RemoteFilesystemsPostv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoteFilesystemsPostv2InternalServerError creates a RemoteFilesystemsPostv2InternalServerError with default headers values
func NewRemoteFilesystemsPostv2InternalServerError() *RemoteFilesystemsPostv2InternalServerError {
	return &RemoteFilesystemsPostv2InternalServerError{}
}

/*RemoteFilesystemsPostv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type RemoteFilesystemsPostv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *RemoteFilesystemsPostv2InternalServerError) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/remotemount/remotefilesystems][%d] remoteFilesystemsPostv2InternalServerError  %+v", 500, o.Payload)
}

func (o *RemoteFilesystemsPostv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *RemoteFilesystemsPostv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
