// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// RemoteClustersPutv2Reader is a Reader for the RemoteClustersPutv2 structure.
type RemoteClustersPutv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoteClustersPutv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewRemoteClustersPutv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewRemoteClustersPutv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewRemoteClustersPutv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewRemoteClustersPutv2Accepted creates a RemoteClustersPutv2Accepted with default headers values
func NewRemoteClustersPutv2Accepted() *RemoteClustersPutv2Accepted {
	return &RemoteClustersPutv2Accepted{}
}

/*RemoteClustersPutv2Accepted handles this case with default header values.

successful operation
*/
type RemoteClustersPutv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *RemoteClustersPutv2Accepted) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/remotemount/remoteclusters/{remoteCluster}][%d] remoteClustersPutv2Accepted  %+v", 202, o.Payload)
}

func (o *RemoteClustersPutv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *RemoteClustersPutv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoteClustersPutv2BadRequest creates a RemoteClustersPutv2BadRequest with default headers values
func NewRemoteClustersPutv2BadRequest() *RemoteClustersPutv2BadRequest {
	return &RemoteClustersPutv2BadRequest{}
}

/*RemoteClustersPutv2BadRequest handles this case with default header values.

Invalid request
*/
type RemoteClustersPutv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *RemoteClustersPutv2BadRequest) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/remotemount/remoteclusters/{remoteCluster}][%d] remoteClustersPutv2BadRequest  %+v", 400, o.Payload)
}

func (o *RemoteClustersPutv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *RemoteClustersPutv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRemoteClustersPutv2InternalServerError creates a RemoteClustersPutv2InternalServerError with default headers values
func NewRemoteClustersPutv2InternalServerError() *RemoteClustersPutv2InternalServerError {
	return &RemoteClustersPutv2InternalServerError{}
}

/*RemoteClustersPutv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type RemoteClustersPutv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *RemoteClustersPutv2InternalServerError) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/remotemount/remoteclusters/{remoteCluster}][%d] remoteClustersPutv2InternalServerError  %+v", 500, o.Payload)
}

func (o *RemoteClustersPutv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *RemoteClustersPutv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
