// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSensorConfigGetOnev2Params creates a new SensorConfigGetOnev2Params object
// with the default values initialized.
func NewSensorConfigGetOnev2Params() *SensorConfigGetOnev2Params {
	var ()
	return &SensorConfigGetOnev2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewSensorConfigGetOnev2ParamsWithTimeout creates a new SensorConfigGetOnev2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewSensorConfigGetOnev2ParamsWithTimeout(timeout time.Duration) *SensorConfigGetOnev2Params {
	var ()
	return &SensorConfigGetOnev2Params{

		timeout: timeout,
	}
}

// NewSensorConfigGetOnev2ParamsWithContext creates a new SensorConfigGetOnev2Params object
// with the default values initialized, and the ability to set a context for a request
func NewSensorConfigGetOnev2ParamsWithContext(ctx context.Context) *SensorConfigGetOnev2Params {
	var ()
	return &SensorConfigGetOnev2Params{

		Context: ctx,
	}
}

// NewSensorConfigGetOnev2ParamsWithHTTPClient creates a new SensorConfigGetOnev2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSensorConfigGetOnev2ParamsWithHTTPClient(client *http.Client) *SensorConfigGetOnev2Params {
	var ()
	return &SensorConfigGetOnev2Params{
		HTTPClient: client,
	}
}

/*SensorConfigGetOnev2Params contains all the parameters to send to the API endpoint
for the sensor config get onev2 operation typically these are written to a http.Request
*/
type SensorConfigGetOnev2Params struct {

	/*Fields
	  Comma separated list of fields to be included in response. ':all:' selects all available fields.

	*/
	Fields *string
	/*SensorName*/
	SensorName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) WithTimeout(timeout time.Duration) *SensorConfigGetOnev2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) WithContext(ctx context.Context) *SensorConfigGetOnev2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) WithHTTPClient(client *http.Client) *SensorConfigGetOnev2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) WithFields(fields *string) *SensorConfigGetOnev2Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithSensorName adds the sensorName to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) WithSensorName(sensorName string) *SensorConfigGetOnev2Params {
	o.SetSensorName(sensorName)
	return o
}

// SetSensorName adds the sensorName to the sensor config get onev2 params
func (o *SensorConfigGetOnev2Params) SetSensorName(sensorName string) {
	o.SensorName = sensorName
}

// WriteToRequest writes these params to a swagger request
func (o *SensorConfigGetOnev2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param sensorName
	if err := r.SetPathParam("sensorName", o.SensorName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
