// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// SmbSharePathPutReader is a Reader for the SmbSharePathPut structure.
type SmbSharePathPutReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SmbSharePathPutReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewSmbSharePathPutAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSmbSharePathPutBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSmbSharePathPutInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSmbSharePathPutAccepted creates a SmbSharePathPutAccepted with default headers values
func NewSmbSharePathPutAccepted() *SmbSharePathPutAccepted {
	return &SmbSharePathPutAccepted{}
}

/*SmbSharePathPutAccepted handles this case with default header values.

successful operation
*/
type SmbSharePathPutAccepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *SmbSharePathPutAccepted) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/smb/shares/{shareName}][%d] smbSharePathPutAccepted  %+v", 202, o.Payload)
}

func (o *SmbSharePathPutAccepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *SmbSharePathPutAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSmbSharePathPutBadRequest creates a SmbSharePathPutBadRequest with default headers values
func NewSmbSharePathPutBadRequest() *SmbSharePathPutBadRequest {
	return &SmbSharePathPutBadRequest{}
}

/*SmbSharePathPutBadRequest handles this case with default header values.

SMB share not found
*/
type SmbSharePathPutBadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *SmbSharePathPutBadRequest) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/smb/shares/{shareName}][%d] smbSharePathPutBadRequest  %+v", 400, o.Payload)
}

func (o *SmbSharePathPutBadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *SmbSharePathPutBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSmbSharePathPutInternalServerError creates a SmbSharePathPutInternalServerError with default headers values
func NewSmbSharePathPutInternalServerError() *SmbSharePathPutInternalServerError {
	return &SmbSharePathPutInternalServerError{}
}

/*SmbSharePathPutInternalServerError handles this case with default header values.

Internal Server Error
*/
type SmbSharePathPutInternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *SmbSharePathPutInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/smb/shares/{shareName}][%d] smbSharePathPutInternalServerError  %+v", 500, o.Payload)
}

func (o *SmbSharePathPutInternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *SmbSharePathPutInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
