// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// SnapshotCopyPathPutv20Reader is a Reader for the SnapshotCopyPathPutv20 structure.
type SnapshotCopyPathPutv20Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SnapshotCopyPathPutv20Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewSnapshotCopyPathPutv20Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSnapshotCopyPathPutv20BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSnapshotCopyPathPutv20InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSnapshotCopyPathPutv20Accepted creates a SnapshotCopyPathPutv20Accepted with default headers values
func NewSnapshotCopyPathPutv20Accepted() *SnapshotCopyPathPutv20Accepted {
	return &SnapshotCopyPathPutv20Accepted{}
}

/*SnapshotCopyPathPutv20Accepted handles this case with default header values.

successful operation
*/
type SnapshotCopyPathPutv20Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *SnapshotCopyPathPutv20Accepted) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/snapshotCopy/{snapshotName}/path/{sourcePath}][%d] snapshotCopyPathPutv20Accepted  %+v", 202, o.Payload)
}

func (o *SnapshotCopyPathPutv20Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *SnapshotCopyPathPutv20Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotCopyPathPutv20BadRequest creates a SnapshotCopyPathPutv20BadRequest with default headers values
func NewSnapshotCopyPathPutv20BadRequest() *SnapshotCopyPathPutv20BadRequest {
	return &SnapshotCopyPathPutv20BadRequest{}
}

/*SnapshotCopyPathPutv20BadRequest handles this case with default header values.

Invalid request
*/
type SnapshotCopyPathPutv20BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *SnapshotCopyPathPutv20BadRequest) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/snapshotCopy/{snapshotName}/path/{sourcePath}][%d] snapshotCopyPathPutv20BadRequest  %+v", 400, o.Payload)
}

func (o *SnapshotCopyPathPutv20BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *SnapshotCopyPathPutv20BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotCopyPathPutv20InternalServerError creates a SnapshotCopyPathPutv20InternalServerError with default headers values
func NewSnapshotCopyPathPutv20InternalServerError() *SnapshotCopyPathPutv20InternalServerError {
	return &SnapshotCopyPathPutv20InternalServerError{}
}

/*SnapshotCopyPathPutv20InternalServerError handles this case with default header values.

Internal Server Error
*/
type SnapshotCopyPathPutv20InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *SnapshotCopyPathPutv20InternalServerError) Error() string {
	return fmt.Sprintf("[PUT /scalemgmt/v2/filesystems/{filesystemName}/snapshotCopy/{snapshotName}/path/{sourcePath}][%d] snapshotCopyPathPutv20InternalServerError  %+v", 500, o.Payload)
}

func (o *SnapshotCopyPathPutv20InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *SnapshotCopyPathPutv20InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
