// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// SnapshotsFilesystemsGetv2Reader is a Reader for the SnapshotsFilesystemsGetv2 structure.
type SnapshotsFilesystemsGetv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SnapshotsFilesystemsGetv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSnapshotsFilesystemsGetv2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSnapshotsFilesystemsGetv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSnapshotsFilesystemsGetv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSnapshotsFilesystemsGetv2OK creates a SnapshotsFilesystemsGetv2OK with default headers values
func NewSnapshotsFilesystemsGetv2OK() *SnapshotsFilesystemsGetv2OK {
	return &SnapshotsFilesystemsGetv2OK{}
}

/*SnapshotsFilesystemsGetv2OK handles this case with default header values.

successful operation
*/
type SnapshotsFilesystemsGetv2OK struct {
	Payload *models.SnapshotInlineResponse200
}

func (o *SnapshotsFilesystemsGetv2OK) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/filesystems/{filesystemName}/snapshots][%d] snapshotsFilesystemsGetv2OK  %+v", 200, o.Payload)
}

func (o *SnapshotsFilesystemsGetv2OK) GetPayload() *models.SnapshotInlineResponse200 {
	return o.Payload
}

func (o *SnapshotsFilesystemsGetv2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SnapshotInlineResponse200)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotsFilesystemsGetv2BadRequest creates a SnapshotsFilesystemsGetv2BadRequest with default headers values
func NewSnapshotsFilesystemsGetv2BadRequest() *SnapshotsFilesystemsGetv2BadRequest {
	return &SnapshotsFilesystemsGetv2BadRequest{}
}

/*SnapshotsFilesystemsGetv2BadRequest handles this case with default header values.

Invalid request
*/
type SnapshotsFilesystemsGetv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *SnapshotsFilesystemsGetv2BadRequest) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/filesystems/{filesystemName}/snapshots][%d] snapshotsFilesystemsGetv2BadRequest  %+v", 400, o.Payload)
}

func (o *SnapshotsFilesystemsGetv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *SnapshotsFilesystemsGetv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotsFilesystemsGetv2InternalServerError creates a SnapshotsFilesystemsGetv2InternalServerError with default headers values
func NewSnapshotsFilesystemsGetv2InternalServerError() *SnapshotsFilesystemsGetv2InternalServerError {
	return &SnapshotsFilesystemsGetv2InternalServerError{}
}

/*SnapshotsFilesystemsGetv2InternalServerError handles this case with default header values.

Internal Server Error
*/
type SnapshotsFilesystemsGetv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *SnapshotsFilesystemsGetv2InternalServerError) Error() string {
	return fmt.Sprintf("[GET /scalemgmt/v2/filesystems/{filesystemName}/snapshots][%d] snapshotsFilesystemsGetv2InternalServerError  %+v", 500, o.Payload)
}

func (o *SnapshotsFilesystemsGetv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *SnapshotsFilesystemsGetv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
