// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// SnapshotsFilesystemSnapshotNameDeletev2Reader is a Reader for the SnapshotsFilesystemSnapshotNameDeletev2 structure.
type SnapshotsFilesystemSnapshotNameDeletev2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SnapshotsFilesystemSnapshotNameDeletev2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewSnapshotsFilesystemSnapshotNameDeletev2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSnapshotsFilesystemSnapshotNameDeletev2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSnapshotsFilesystemSnapshotNameDeletev2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSnapshotsFilesystemSnapshotNameDeletev2Accepted creates a SnapshotsFilesystemSnapshotNameDeletev2Accepted with default headers values
func NewSnapshotsFilesystemSnapshotNameDeletev2Accepted() *SnapshotsFilesystemSnapshotNameDeletev2Accepted {
	return &SnapshotsFilesystemSnapshotNameDeletev2Accepted{}
}

/*SnapshotsFilesystemSnapshotNameDeletev2Accepted handles this case with default header values.

successful operation
*/
type SnapshotsFilesystemSnapshotNameDeletev2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2Accepted) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/snapshots/{snapshotName}][%d] snapshotsFilesystemSnapshotNameDeletev2Accepted  %+v", 202, o.Payload)
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotsFilesystemSnapshotNameDeletev2BadRequest creates a SnapshotsFilesystemSnapshotNameDeletev2BadRequest with default headers values
func NewSnapshotsFilesystemSnapshotNameDeletev2BadRequest() *SnapshotsFilesystemSnapshotNameDeletev2BadRequest {
	return &SnapshotsFilesystemSnapshotNameDeletev2BadRequest{}
}

/*SnapshotsFilesystemSnapshotNameDeletev2BadRequest handles this case with default header values.

Invalid request
*/
type SnapshotsFilesystemSnapshotNameDeletev2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2BadRequest) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/snapshots/{snapshotName}][%d] snapshotsFilesystemSnapshotNameDeletev2BadRequest  %+v", 400, o.Payload)
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSnapshotsFilesystemSnapshotNameDeletev2InternalServerError creates a SnapshotsFilesystemSnapshotNameDeletev2InternalServerError with default headers values
func NewSnapshotsFilesystemSnapshotNameDeletev2InternalServerError() *SnapshotsFilesystemSnapshotNameDeletev2InternalServerError {
	return &SnapshotsFilesystemSnapshotNameDeletev2InternalServerError{}
}

/*SnapshotsFilesystemSnapshotNameDeletev2InternalServerError handles this case with default header values.

Internal Server Error
*/
type SnapshotsFilesystemSnapshotNameDeletev2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2InternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /scalemgmt/v2/filesystems/{filesystemName}/snapshots/{snapshotName}][%d] snapshotsFilesystemSnapshotNameDeletev2InternalServerError  %+v", 500, o.Payload)
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *SnapshotsFilesystemSnapshotNameDeletev2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
