// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSpecificationsGetParams creates a new SpecificationsGetParams object
// with the default values initialized.
func NewSpecificationsGetParams() *SpecificationsGetParams {
	var ()
	return &SpecificationsGetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSpecificationsGetParamsWithTimeout creates a new SpecificationsGetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSpecificationsGetParamsWithTimeout(timeout time.Duration) *SpecificationsGetParams {
	var ()
	return &SpecificationsGetParams{

		timeout: timeout,
	}
}

// NewSpecificationsGetParamsWithContext creates a new SpecificationsGetParams object
// with the default values initialized, and the ability to set a context for a request
func NewSpecificationsGetParamsWithContext(ctx context.Context) *SpecificationsGetParams {
	var ()
	return &SpecificationsGetParams{

		Context: ctx,
	}
}

// NewSpecificationsGetParamsWithHTTPClient creates a new SpecificationsGetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSpecificationsGetParamsWithHTTPClient(client *http.Client) *SpecificationsGetParams {
	var ()
	return &SpecificationsGetParams{
		HTTPClient: client,
	}
}

/*SpecificationsGetParams contains all the parameters to send to the API endpoint
for the specifications get operation typically these are written to a http.Request
*/
type SpecificationsGetParams struct {

	/*Fields
	  Comma separated list of fields to be included in response. ':all:' selects all available fields.

	*/
	Fields *string
	/*Filter
	  Filter objects by expression, e.g. 'status=HEALTHY,entityType=FILESET'

	*/
	Filter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the specifications get params
func (o *SpecificationsGetParams) WithTimeout(timeout time.Duration) *SpecificationsGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the specifications get params
func (o *SpecificationsGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the specifications get params
func (o *SpecificationsGetParams) WithContext(ctx context.Context) *SpecificationsGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the specifications get params
func (o *SpecificationsGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the specifications get params
func (o *SpecificationsGetParams) WithHTTPClient(client *http.Client) *SpecificationsGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the specifications get params
func (o *SpecificationsGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the specifications get params
func (o *SpecificationsGetParams) WithFields(fields *string) *SpecificationsGetParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the specifications get params
func (o *SpecificationsGetParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithFilter adds the filter to the specifications get params
func (o *SpecificationsGetParams) WithFilter(filter *string) *SpecificationsGetParams {
	o.SetFilter(filter)
	return o
}

// SetFilter adds the filter to the specifications get params
func (o *SpecificationsGetParams) SetFilter(filter *string) {
	o.Filter = filter
}

// WriteToRequest writes these params to a swagger request
func (o *SpecificationsGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Filter != nil {

		// query param filter
		var qrFilter string
		if o.Filter != nil {
			qrFilter = *o.Filter
		}
		qFilter := qrFilter
		if qFilter != "" {
			if err := r.SetQueryParam("filter", qFilter); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
