// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// SymlinkPostv2Reader is a Reader for the SymlinkPostv2 structure.
type SymlinkPostv2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SymlinkPostv2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewSymlinkPostv2Accepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSymlinkPostv2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewSymlinkPostv2InternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewSymlinkPostv2Accepted creates a SymlinkPostv2Accepted with default headers values
func NewSymlinkPostv2Accepted() *SymlinkPostv2Accepted {
	return &SymlinkPostv2Accepted{}
}

/*SymlinkPostv2Accepted handles this case with default header values.

successful operation
*/
type SymlinkPostv2Accepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *SymlinkPostv2Accepted) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/symlink/{linkPath}][%d] symlinkPostv2Accepted  %+v", 202, o.Payload)
}

func (o *SymlinkPostv2Accepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *SymlinkPostv2Accepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSymlinkPostv2BadRequest creates a SymlinkPostv2BadRequest with default headers values
func NewSymlinkPostv2BadRequest() *SymlinkPostv2BadRequest {
	return &SymlinkPostv2BadRequest{}
}

/*SymlinkPostv2BadRequest handles this case with default header values.

Invalid file system or path
*/
type SymlinkPostv2BadRequest struct {
	Payload *models.Http400BadRequest
}

func (o *SymlinkPostv2BadRequest) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/symlink/{linkPath}][%d] symlinkPostv2BadRequest  %+v", 400, o.Payload)
}

func (o *SymlinkPostv2BadRequest) GetPayload() *models.Http400BadRequest {
	return o.Payload
}

func (o *SymlinkPostv2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http400BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSymlinkPostv2InternalServerError creates a SymlinkPostv2InternalServerError with default headers values
func NewSymlinkPostv2InternalServerError() *SymlinkPostv2InternalServerError {
	return &SymlinkPostv2InternalServerError{}
}

/*SymlinkPostv2InternalServerError handles this case with default header values.

An unexpected error occurred.
*/
type SymlinkPostv2InternalServerError struct {
	Payload *models.Http500InternalServerError
}

func (o *SymlinkPostv2InternalServerError) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/symlink/{linkPath}][%d] symlinkPostv2InternalServerError  %+v", 500, o.Payload)
}

func (o *SymlinkPostv2InternalServerError) GetPayload() *models.Http500InternalServerError {
	return o.Payload
}

func (o *SymlinkPostv2InternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Http500InternalServerError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
