// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewThresholdGetv2Params creates a new ThresholdGetv2Params object
// with the default values initialized.
func NewThresholdGetv2Params() *ThresholdGetv2Params {
	var ()
	return &ThresholdGetv2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewThresholdGetv2ParamsWithTimeout creates a new ThresholdGetv2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewThresholdGetv2ParamsWithTimeout(timeout time.Duration) *ThresholdGetv2Params {
	var ()
	return &ThresholdGetv2Params{

		timeout: timeout,
	}
}

// NewThresholdGetv2ParamsWithContext creates a new ThresholdGetv2Params object
// with the default values initialized, and the ability to set a context for a request
func NewThresholdGetv2ParamsWithContext(ctx context.Context) *ThresholdGetv2Params {
	var ()
	return &ThresholdGetv2Params{

		Context: ctx,
	}
}

// NewThresholdGetv2ParamsWithHTTPClient creates a new ThresholdGetv2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewThresholdGetv2ParamsWithHTTPClient(client *http.Client) *ThresholdGetv2Params {
	var ()
	return &ThresholdGetv2Params{
		HTTPClient: client,
	}
}

/*ThresholdGetv2Params contains all the parameters to send to the API endpoint
for the threshold getv2 operation typically these are written to a http.Request
*/
type ThresholdGetv2Params struct {

	/*Fields
	  Comma separated list of fields to be included in response. ':all:' selects all available fields.

	*/
	Fields *string
	/*Name
	  threshold rule name

	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the threshold getv2 params
func (o *ThresholdGetv2Params) WithTimeout(timeout time.Duration) *ThresholdGetv2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the threshold getv2 params
func (o *ThresholdGetv2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the threshold getv2 params
func (o *ThresholdGetv2Params) WithContext(ctx context.Context) *ThresholdGetv2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the threshold getv2 params
func (o *ThresholdGetv2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the threshold getv2 params
func (o *ThresholdGetv2Params) WithHTTPClient(client *http.Client) *ThresholdGetv2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the threshold getv2 params
func (o *ThresholdGetv2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the threshold getv2 params
func (o *ThresholdGetv2Params) WithFields(fields *string) *ThresholdGetv2Params {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the threshold getv2 params
func (o *ThresholdGetv2Params) SetFields(fields *string) {
	o.Fields = fields
}

// WithName adds the name to the threshold getv2 params
func (o *ThresholdGetv2Params) WithName(name string) *ThresholdGetv2Params {
	o.SetName(name)
	return o
}

// SetName adds the name to the threshold getv2 params
func (o *ThresholdGetv2Params) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *ThresholdGetv2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
