// Code generated by go-swagger; DO NOT EDIT.

package spectrum_scale_r_e_s_t_api_v2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"example.com/m/v2/models"
)

// UploadReader is a Reader for the Upload structure.
type UploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewUploadAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewUploadInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUploadAccepted creates a UploadAccepted with default headers values
func NewUploadAccepted() *UploadAccepted {
	return &UploadAccepted{}
}

/*UploadAccepted handles this case with default header values.

successful operation
*/
type UploadAccepted struct {
	Payload *models.AsyncRequestResponse
}

func (o *UploadAccepted) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/cos/upload][%d] uploadAccepted  %+v", 202, o.Payload)
}

func (o *UploadAccepted) GetPayload() *models.AsyncRequestResponse {
	return o.Payload
}

func (o *UploadAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AsyncRequestResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadInternalServerError creates a UploadInternalServerError with default headers values
func NewUploadInternalServerError() *UploadInternalServerError {
	return &UploadInternalServerError{}
}

/*UploadInternalServerError handles this case with default header values.

Internal Server Error
*/
type UploadInternalServerError struct {
	Payload *models.RequestStatus
}

func (o *UploadInternalServerError) Error() string {
	return fmt.Sprintf("[POST /scalemgmt/v2/filesystems/{filesystemName}/filesets/{filesetName}/cos/upload][%d] uploadInternalServerError  %+v", 500, o.Payload)
}

func (o *UploadInternalServerError) GetPayload() *models.RequestStatus {
	return o.Payload
}

func (o *UploadInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RequestStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
