---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options: {}
lint: |
  set -e
  yamllint .
#  ansible-lint
#  flake8
platforms:
  - name: test-cluster
    groups:
      - k8s
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        namespace: ibm-spectrum-scale-csi-driver
  env:
    KUBECONFIG: ${KUBECONFIG:-$HOME/.kube/config}
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-$HOME/.kube/config}
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/roles
scenario:
  name: test-cluster
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
