---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: ibm-spectrum-scale-csi

resources:
- ../../rbac/
- ../../manager/
- ../../crd/
- ../../scc/

patches:
  - target:
      kind: Deployment
      labelSelector: "app.kubernetes.io/name=ibm-spectrum-scale-csi-operator"
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ibm-spectrum-scale-csi-operator
      spec:
        template:
          spec:
            containers:
              - name: operator
                env:
                  # do not remove: this is required for CNSA; SHORTNAME_NODE_MAPPING="yes" for split hostNetwork node mapping.
                  - name: SHORTNAME_NODE_MAPPING
                    value: "yes"
                  - name: CSI_SNAPSHOTTER_IMAGE
                    value: cp.icr.io/cp/gpfs/csi/csi-snapshotter@sha256:42af0929bcd60a43499825c078a60ff0534e08af8fbeb283aa391be40feb9f3e
                  - name: CSI_ATTACHER_IMAGE
                    value: cp.icr.io/cp/gpfs/csi/csi-attacher@sha256:b9dc9a714a484ccdeeb6f86d88d4db9b7a5ecfc5a55da6db3a60bb3fa33c278a
                  - name: CSI_PROVISIONER_IMAGE
                    value: cp.icr.io/cp/gpfs/csi/csi-provisioner@sha256:a4b0b1a37605b7b04a293e136edf7006ec1786a8eb3f4e5a945f81d667dcc371
                  - name: CSI_LIVENESSPROBE_IMAGE
                    value: cp.icr.io/cp/gpfs/csi/livenessprobe@sha256:06da0d5b8908072f2e4522692aee8dc119fba7247a9658497e1153992cd777e9
                  - name: CSI_NODE_REGISTRAR_IMAGE
                    value: cp.icr.io/cp/gpfs/csi/csi-node-driver-registrar@sha256:f9de845b170155199f2a2a3f9531cf13d78e31235e9db6b6582a8b0db0a50dad
                  - name: CSI_RESIZER_IMAGE
                    value: cp.icr.io/cp/gpfs/csi/csi-resizer@sha256:ea1d25e23479000c7e8eeb92d827df66258df4e482ca054c5e7ce3fc0f5c41a5
                  - name: CSI_DRIVER_IMAGE
                    value: cp.icr.io/cp/gpfs/csi/ibm-spectrum-scale-csi-driver@sha256:a03f233a1e4276310bc008d6eb04de910408d3ef711f79b4e82d72ffa4ae5a4e
                image: icr.io/cpopen/ibm-spectrum-scale-csi-operator@sha256:45d763e7d5810914dc345cf81d5a095921c9cd4fe1746f5f0f3c50fa91930541
