- name: "Get timestamp"
  shell: "date +%s"
  register: tstamp

- name: "Determing directory for temporary package"
  set_fact:
    olm_dir: "/tmp/operator-pkg-{{tstamp.stdout}}"

- name: "Create the directory {{ olm_dir }}"
  file:
    path: "{{ olm_dir }}"
    state: directory
    mode: '0755'

- name: "Create the build dir"
  file:
    path: "{{ OUTPUT }}"
    state: directory
    mode: '0755'



- name: "Archive without flattening"
  when: flatten == false
  block: 
    - name: "Copy {{OLM_BASE}} to {{olm_dir}}"
      copy:
        src: "{{OLM_BASE}}/"
        dest: "{{olm_dir}}"

    - name:  "Archive the bundle: {{OUTPUT}}/{{package_name}}.zip"
      archive:
        path: "{{olm_dir}}"
        format: zip
        dest: "{{OUTPUT}}/{{package_name}}.zip"

- name: "Archive with flattening"
  when: flatten
  block:
    - name:  "Copy package"
      copy:
        src: "{{OLM_BASE}}/ibm-spectrum-scale-csi-operator.package.yaml"
        dest: "{{olm_dir}}"

    - name: "Load the package into ansible"
      include_vars:
        file: "{{olm_dir}}/ibm-spectrum-scale-csi-operator.package.yaml"
        name: package

    - name: "Get channel version"
      set_fact:
        currentVersion: "{{ package.channels[0].currentCSV.split('.v')[1] }}"
        #currentCSV: "{{ package.json.data | json_query('channels[*][?name==`package.defaultChannel`][0].currentCSV[0]') }}"
    
    - name: "Find all of the CSV in the OLM directory" 
      find:
        paths: "{{OLM_BASE}}"
        contains:  ".*clusterserviceversion.*"
        depth: 2
        recurse: yes
      register: csvs

    - debug:
        var: csvs
    - name: "Copy CSVs to  {{olm_dir}}"
      copy:
        src: "{{item.path}}"
        dest: "{{olm_dir}}"
      with_items: "{{ csvs.files }}"

    - name: "Find all of the configs for the current version"
      find:
        paths: "{{OLM_BASE}}/{{currentVersion}}"
      register: configs

    - debug: 
        var: configs
    - name: "Copy configs to  {{olm_dir}}"
      copy:
        src: "{{item.path}}"
        dest: "{{olm_dir}}"
      with_items: "{{ configs.files }}"

    - name:  "Archive the bundle: {{OUTPUT}}/{{package_name}}.zip"
      archive:
        path: "{{olm_dir}}"
        format: zip
        dest: "{{OUTPUT}}/{{package_name}}.zip"


- name: "Remove the directory {{ olm_dir }}"
  file:
    path: "{{ olm_dir }}"
    state: absent
    mode: '0755'
