---
scorecard:
  init-timeout: 120
  output: json
  bundle: "config/olm-catalog/ibm-spectrum-scale-csi-operator/2.2.0"
  plugins:
    - basic:
        namespace: "ibm-spectrum-scale-csi-driver"
        cr-manifest:
          - "config/samples/csiscaleoperators.csi.ibm.com_cr.yaml"
    - olm:
        namespace: "ibm-spectrum-scale-csi-driver"
        cr-manifest:
          - "config/samples/csiscaleoperators.csi.ibm.com_cr.yaml"
        csv-path: "config/olm-catalog/ibm-spectrum-scale-csi-operator/2.2.0/ibm-spectrum-scale-csi-operator.v2.2.0.clusterserviceversion.yaml"
