
actions:
  metadata:
    displayDescription: "Represents a deployment of the IBM CSI Storage Scale driver."
    displayName: "IBM CSI Storage Scale Driver"
    name: "ibmCSIScaleOperator"
    description: "Represents a deployment of the IBM CSI Storage Scale driver."
  actionDefs:
    applyCustomResources:
      metadata :
        name: applyCustomResources
        displayName: applyCustomResources
        displayDescription: Install the IBM Storage Scale CSI Driver Instance
        #case.launcher.type: "script"
        #case.launcher.isdefault: true
        #case.cli.alias: "apply-custom-resources"
      roles:
      - namespaceAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The applyCustomResources action must be run on OpenShift Container Platform on amd64 Linux. The minimum
              level of Kubernetes on each platform are described in the CASE prerequisites. The ibm-spectrum-scale-csi-operator CustomResourceDefintion
              and SecurityContextConstraints described in the CASE prerequisites must also exist on the Cluster. The client
              must have kubectl and oc installed to execute the launcher script.
        and:
        - "/case/prereqs/k8sDistros/kubernetes"
        - or:
          - "/case/prereqs/client/kubectl"
          - "/case/prereqs/client/oc"
          - and:
            - "/case/prereqs/k8sDistros/openshift"
            - "/case/prereqs/k8sResources/restrictedSCC"
      k8sPermissions:
        rules:
        - rule:
            group: csiscaleoperators.csi.ibm.com
            resource: '*'
            verbs:
            - get
            - list
            - watch
            - create
            - patch
            - update
    deleteCustomResources:
      metadata :
        name: deleteCustomResources
        displayName: deleteCustomResources
        displayDescription: Uninstall the IBM Storage Scale CSI Driver Instance
        #case.launcher.type: "script"
        #case.cli.alias: "delete-custom-resources"
      roles:
      - namespaceAdmin
      k8sPermissions:
        rules:
        - rule:
            group: csiscaleoperators.csi.ibm.com
            resource: '*'
            verbs:
            - '*'
