// Code generated by go-swagger; DO NOT EDIT.

package api_discovery

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"example.com/m/v2/models"
)

// PostSubscriptionReader is a Reader for the PostSubscription structure.
type PostSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostSubscriptionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewPostSubscriptionMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostSubscriptionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostSubscriptionOK creates a PostSubscriptionOK with default headers values
func NewPostSubscriptionOK() *PostSubscriptionOK {
	return &PostSubscriptionOK{}
}

/*PostSubscriptionOK handles this case with default header values.

A JSON payload outlining the type of subscription feed and its URL
*/
type PostSubscriptionOK struct {
	Payload *models.SubscriptionResponse
}

func (o *PostSubscriptionOK) Error() string {
	return fmt.Sprintf("[POST /ibm/api/docs/subscription][%d] postSubscriptionOK  %+v", 200, o.Payload)
}

func (o *PostSubscriptionOK) GetPayload() *models.SubscriptionResponse {
	return o.Payload
}

func (o *PostSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SubscriptionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostSubscriptionBadRequest creates a PostSubscriptionBadRequest with default headers values
func NewPostSubscriptionBadRequest() *PostSubscriptionBadRequest {
	return &PostSubscriptionBadRequest{}
}

/*PostSubscriptionBadRequest handles this case with default header values.

Bad Request. The request could not be understood by the server due to malformed syntax. Please ensure that the input payload is valid
*/
type PostSubscriptionBadRequest struct {
}

func (o *PostSubscriptionBadRequest) Error() string {
	return fmt.Sprintf("[POST /ibm/api/docs/subscription][%d] postSubscriptionBadRequest ", 400)
}

func (o *PostSubscriptionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostSubscriptionMethodNotAllowed creates a PostSubscriptionMethodNotAllowed with default headers values
func NewPostSubscriptionMethodNotAllowed() *PostSubscriptionMethodNotAllowed {
	return &PostSubscriptionMethodNotAllowed{}
}

/*PostSubscriptionMethodNotAllowed handles this case with default header values.

Method not allowed
*/
type PostSubscriptionMethodNotAllowed struct {
}

func (o *PostSubscriptionMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /ibm/api/docs/subscription][%d] postSubscriptionMethodNotAllowed ", 405)
}

func (o *PostSubscriptionMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostSubscriptionInternalServerError creates a PostSubscriptionInternalServerError with default headers values
func NewPostSubscriptionInternalServerError() *PostSubscriptionInternalServerError {
	return &PostSubscriptionInternalServerError{}
}

/*PostSubscriptionInternalServerError handles this case with default header values.

An internal error has occurred. Ensure either 'websocket-1.0' or 'websocket-1.1' is configured in the 'server.xml'
*/
type PostSubscriptionInternalServerError struct {
}

func (o *PostSubscriptionInternalServerError) Error() string {
	return fmt.Sprintf("[POST /ibm/api/docs/subscription][%d] postSubscriptionInternalServerError ", 500)
}

func (o *PostSubscriptionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*PostSubscriptionBody post subscription body
swagger:model PostSubscriptionBody
*/
type PostSubscriptionBody struct {

	// Format of the update
	// Enum: [Swagger_20_JSON Swagger_20_YAML]
	DocType *string `json:"docType,omitempty"`
}

// Validate validates this post subscription body
func (o *PostSubscriptionBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDocType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var postSubscriptionBodyTypeDocTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Swagger_20_JSON","Swagger_20_YAML"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		postSubscriptionBodyTypeDocTypePropEnum = append(postSubscriptionBodyTypeDocTypePropEnum, v)
	}
}

const (

	// PostSubscriptionBodyDocTypeSwagger20JSON captures enum value "Swagger_20_JSON"
	PostSubscriptionBodyDocTypeSwagger20JSON string = "Swagger_20_JSON"

	// PostSubscriptionBodyDocTypeSwagger20YAML captures enum value "Swagger_20_YAML"
	PostSubscriptionBodyDocTypeSwagger20YAML string = "Swagger_20_YAML"
)

// prop value enum
func (o *PostSubscriptionBody) validateDocTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, postSubscriptionBodyTypeDocTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *PostSubscriptionBody) validateDocType(formats strfmt.Registry) error {

	if swag.IsZero(o.DocType) { // not required
		return nil
	}

	// value enum
	if err := o.validateDocTypeEnum("body"+"."+"docType", "body", *o.DocType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostSubscriptionBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostSubscriptionBody) UnmarshalBinary(b []byte) error {
	var res PostSubscriptionBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
